import type { HealingAdapter, HealingAdapterConfig } from './base.js';

/**
 * Appium Java healing adapter.
 *
 * Generates:
 * 1. src/test/java/healing/HealingClient.java — HTTP client for qabot healing API
 * 2. src/test/java/healing/HealingDriver.java — Wrapper for AppiumDriver with self-healing
 */
export const appiumJavaAdapter: HealingAdapter = {
  framework: 'appium',
  language: 'java',
  displayName: 'Appium (Java)',

  generate(config: HealingAdapterConfig): Record<string, string> {
    const files: Record<string, string> = {};

    // ── Healing Client ─────────────────────────────────────────────────────
    files['src/test/java/healing/HealingClient.java'] = `package healing;

/**
 * qabot Healing Client — HTTP bridge to qabot's self-healing API.
 * Auto-generated by qabot. Do not edit manually.
 */

import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import com.google.gson.*;
import com.google.gson.reflect.TypeToken;

public class HealingClient {
    private static final String HEALING_SERVER = "${config.healingServerUrl}";
    private static final double CONFIDENCE_THRESHOLD = ${config.confidenceThreshold};
    private static final String FRAMEWORK = "appium";
    private static final String LANGUAGE = "java";

    private final String serverUrl;
    private final Gson gson = new Gson();

    public HealingClient() {
        this(HEALING_SERVER);
    }

    public HealingClient(String serverUrl) {
        this.serverUrl = serverUrl;
    }

    public void storeFingerprint(String selectorKey, String url, JsonObject fingerprint) {
        try {
            JsonObject body = new JsonObject();
            body.addProperty("selectorKey", selectorKey);
            body.addProperty("url", url);
            body.add("fingerprint", fingerprint);
            body.addProperty("framework", FRAMEWORK);
            postJson("/api/heal/fingerprint", body);
        } catch (Exception ignored) {
            // qabot server not running — continue silently
        }
    }

    public HealResult resolve(String selector, String pageUrl) {
        return resolve(selector, pageUrl, null, null);
    }

    public HealResult resolve(String selector, String pageUrl, JsonObject fingerprint) {
        return resolve(selector, pageUrl, fingerprint, null);
    }

    public HealResult resolve(String selector, String pageUrl, JsonObject fingerprint, String errorMessage) {
        try {
            JsonObject body = new JsonObject();
            body.addProperty("selector", selector);
            body.addProperty("selectorStrategy", "css");
            body.addProperty("pageUrl", pageUrl);
            body.addProperty("framework", FRAMEWORK);
            body.addProperty("language", LANGUAGE);
            if (fingerprint != null) {
                body.add("fingerprint", fingerprint);
            }
            if (errorMessage != null) {
                body.addProperty("errorMessage", errorMessage);
            }

            String response = postJson("/api/heal/resolve", body);
            if (response == null) return null;

            JsonObject result = JsonParser.parseString(response).getAsJsonObject();
            if (result.has("healed") && result.get("healed").getAsBoolean()) {
                double confidence = result.has("confidence") ? result.get("confidence").getAsDouble() : 0;
                if (confidence >= CONFIDENCE_THRESHOLD) {
                    List<HealCandidate> candidates = parseCandidates(result);
                    return new HealResult(
                        true,
                        result.has("selector") ? result.get("selector").getAsString() : null,
                        confidence,
                        result.has("strategy") ? result.get("strategy").getAsString() : null,
                        result.has("durationMs") ? result.get("durationMs").getAsInt() : 0,
                        candidates
                    );
                }
            }
        } catch (Exception ignored) {
        }
        return null;
    }

    /**
     * Request AI text-based healing (LLM fallback — Phase 2).
     */
    public HealResult resolveAI(String selector, String pageUrl, String errorMessage) {
        return resolveAI(selector, pageUrl, errorMessage, null);
    }

    public HealResult resolveAI(String selector, String pageUrl, String errorMessage, java.util.Map<String, String> testContext) {
        try {
            JsonObject body = new JsonObject();
            body.addProperty("selector", selector);
            body.addProperty("selectorStrategy", "css");
            body.addProperty("pageUrl", pageUrl);
            body.addProperty("framework", FRAMEWORK);
            body.addProperty("language", LANGUAGE);
            if (errorMessage != null) body.addProperty("errorMessage", errorMessage);
            body.addProperty("requestAI", true);
            if (testContext != null && !testContext.isEmpty()) {
                body.add("testContext", gson.toJsonTree(testContext));
            }

            String response = postJson("/api/heal/resolve", body);
            if (response == null) return null;

            JsonObject result = JsonParser.parseString(response).getAsJsonObject();
            if (result.has("healed") && result.get("healed").getAsBoolean()) {
                return new HealResult(
                    true,
                    result.has("selector") ? result.get("selector").getAsString() : null,
                    result.has("confidence") ? result.get("confidence").getAsDouble() : 0,
                    result.has("strategy") ? result.get("strategy").getAsString() : "aiHealing",
                    result.has("durationMs") ? result.get("durationMs").getAsInt() : 0
                );
            }
        } catch (Exception ignored) {
        }
        return null;
    }

    /**
     * Request Vision healing via screenshot + multimodal LLM (Phase 3).
     */
    public HealResult resolveVision(String selector, String pageUrl, String screenshotBase64) {
        return resolveVision(selector, pageUrl, screenshotBase64, null);
    }

    public HealResult resolveVision(String selector, String pageUrl, String screenshotBase64, java.util.Map<String, String> testContext) {
        try {
            JsonObject body = new JsonObject();
            body.addProperty("selector", selector);
            body.addProperty("pageUrl", pageUrl);
            body.addProperty("screenshotBase64", screenshotBase64);
            body.addProperty("framework", FRAMEWORK);
            body.addProperty("language", LANGUAGE);
            if (testContext != null) {
                if (testContext.containsKey("errorMessage")) body.addProperty("errorMessage", testContext.get("errorMessage"));
                if (!testContext.isEmpty()) body.add("testContext", gson.toJsonTree(testContext));
            }

            String response = postJson("/api/heal/vision", body);
            if (response == null) return null;

            JsonObject result = JsonParser.parseString(response).getAsJsonObject();
            if (result.has("healed") && result.get("healed").getAsBoolean()) {
                return new HealResult(
                    true,
                    result.has("selector") ? result.get("selector").getAsString() : null,
                    result.has("confidence") ? result.get("confidence").getAsDouble() : 0,
                    "visionHealing",
                    result.has("durationMs") ? result.get("durationMs").getAsInt() : 0
                );
            }
        } catch (Exception ignored) {
        }
        return null;
    }

    private List<HealCandidate> parseCandidates(JsonObject result) {
        List<HealCandidate> list = new ArrayList<>();
        if (result.has("candidates") && result.get("candidates").isJsonArray()) {
            JsonArray arr = result.getAsJsonArray("candidates");
            for (JsonElement el : arr) {
                if (el.isJsonObject()) {
                    HealCandidate c = gson.fromJson(el, HealCandidate.class);
                    if (c != null && c.selector != null) list.add(c);
                }
            }
        }
        return list;
    }

    public void report(String selectorKey, String url, boolean healed,
                       String healedSelector, double confidence, String strategy, int durationMs) {
        try {
            JsonObject body = new JsonObject();
            body.addProperty("selectorKey", selectorKey);
            body.addProperty("url", url);
            body.addProperty("healed", healed);
            if (healedSelector != null) body.addProperty("healedSelector", healedSelector);
            body.addProperty("confidence", confidence);
            if (strategy != null) body.addProperty("strategy", strategy);
            body.addProperty("framework", FRAMEWORK);
            body.addProperty("language", LANGUAGE);
            body.addProperty("originalSelector", selectorKey);
            body.addProperty("durationMs", durationMs);
            postJson("/api/heal/report", body);
        } catch (Exception ignored) {
        }
    }

    private String postJson(String path, JsonObject body) throws Exception {
        URL url = new URL(serverUrl + path);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("POST");
        conn.setRequestProperty("Content-Type", "application/json");
        conn.setConnectTimeout(5000);
        conn.setReadTimeout(10000);
        conn.setDoOutput(true);

        try (OutputStream os = conn.getOutputStream()) {
            os.write(body.toString().getBytes(StandardCharsets.UTF_8));
        }

        int code = conn.getResponseCode();
        if (code >= 200 && code < 300) {
            try (BufferedReader br = new BufferedReader(
                    new InputStreamReader(conn.getInputStream(), StandardCharsets.UTF_8))) {
                StringBuilder sb = new StringBuilder();
                String line;
                while ((line = br.readLine()) != null) sb.append(line);
                return sb.toString();
            }
        }
        return null;
    }

    public static class HealCandidate {
        public String selector;
        public String strategy;
    }

    public static class HealResult {
        public final boolean healed;
        public final String selector;
        public final double confidence;
        public final String strategy;
        public final int durationMs;
        public final List<HealCandidate> candidates;

        public HealResult(boolean healed, String selector, double confidence, String strategy, int durationMs) {
            this(healed, selector, confidence, strategy, durationMs, null);
        }

        public HealResult(boolean healed, String selector, double confidence, String strategy, int durationMs, List<HealCandidate> candidates) {
            this.healed = healed;
            this.selector = selector;
            this.confidence = confidence;
            this.strategy = strategy;
            this.durationMs = durationMs;
            this.candidates = candidates;
        }
    }
}
`;

    // ── Healing Driver ─────────────────────────────────────────────────────
    files['src/test/java/healing/HealingDriver.java'] = `package healing;

/**
 * qabot Self-Healing Appium Driver Wrapper.
 * Auto-generated by qabot. Do not edit manually.
 *
 * Wraps AppiumDriver element-finding methods with self-healing.
 * On element-not-found: queries qabot API for healed selectors and retries.
 * On success: captures element fingerprints for baseline.
 *
 * Usage:
 *   AppiumDriver driver = new AndroidDriver(url, caps);
 *   HealingDriver healing = new HealingDriver(driver);
 *   WebElement el = healing.findElement(By.id("login-btn"));
 */

import io.appium.java_client.AppiumDriver;
import org.openqa.selenium.*;
import com.google.gson.*;
import java.util.List;

public class HealingDriver {
    private final AppiumDriver driver;
    private final HealingClient client;
    private int healedCount = 0;

    public HealingDriver(AppiumDriver driver) {
        this(driver, new HealingClient());
    }

    public HealingDriver(AppiumDriver driver, HealingClient client) {
        this.driver = driver;
        this.client = client;
    }

    public AppiumDriver getDriver() {
        return driver;
    }

    public int getHealedCount() {
        return healedCount;
    }

    /**
     * Find element with self-healing (3-phase strategy chain).
     */
    public WebElement findElement(By by) {
        String selector = byToSelector(by);
        String url = getCurrentUrl();
        long start = System.currentTimeMillis();

        try {
            WebElement element = driver.findElement(by);
            // Success — store fingerprint
            storeFingerprint(selector, url, element);
            return element;
        } catch (NoSuchElementException original) {
            String selectorKey = "css:" + selector;
            String errorMsg = original.getMessage();

            // ── Phase 1: Deterministic candidates (fingerprint, similarSelector, textMatch, ancestorSearch) ──
            HealingClient.HealResult result = client.resolve(selector, url, null, errorMsg);
            if (result != null && result.selector != null && !result.selector.equals(selector)) {
                // Build ordered candidate list: best match first, then remaining candidates
                java.util.List<HealingClient.HealCandidate> candidates = new java.util.ArrayList<>();
                HealingClient.HealCandidate best = new HealingClient.HealCandidate();
                best.selector = result.selector;
                best.strategy = result.strategy != null ? result.strategy : "fingerprint";
                candidates.add(best);
                if (result.candidates != null) {
                    for (HealingClient.HealCandidate c : result.candidates) {
                        if (c.selector != null && !c.selector.equals(selector) && !c.selector.equals(result.selector)) {
                            candidates.add(c);
                        }
                    }
                }

                for (int i = 0; i < candidates.size(); i++) {
                    HealingClient.HealCandidate candidate = candidates.get(i);
                    System.out.println("[qabot-heal] " + (i == 0 ? "Trying" : "Fallback") + ": \\"" + selector + "\\" → \\"" + candidate.selector + "\\" " +
                        "(strategy: " + candidate.strategy + (i > 0 ? ", attempt " + (i + 1) + "/" + candidates.size() : "") + ")");
                    try {
                        By healedBy = selectorToBy(candidate.selector);
                        WebElement element = driver.findElement(healedBy);
                        int duration = (int)(System.currentTimeMillis() - start);
                        client.report(selectorKey, url, true, candidate.selector, result.confidence, candidate.strategy, duration);
                        storeFingerprint(candidate.selector, url, element);
                        healedCount++;
                        return element;
                    } catch (NoSuchElementException healFail) {
                        // This candidate failed — try next
                    }
                }
            }

            // ── Phase 2: AI text-based healing (LLM fallback) ──
            try {
                HealingClient.HealResult aiResult = client.resolveAI(selector, url, errorMsg, null);
                if (aiResult != null && aiResult.selector != null && !aiResult.selector.equals(selector)) {
                    System.out.println("[qabot-heal] AI: \\"" + selector + "\\" → \\"" + aiResult.selector + "\\" " +
                        "(confidence: " + Math.round(aiResult.confidence * 100) + "%, strategy: aiHealing)");
                    try {
                        By healedBy = selectorToBy(aiResult.selector);
                        WebElement element = driver.findElement(healedBy);
                        int duration = (int)(System.currentTimeMillis() - start);
                        client.report(selectorKey, url, true, aiResult.selector, aiResult.confidence, "aiHealing", duration);
                        storeFingerprint(aiResult.selector, url, element);
                        healedCount++;
                        return element;
                    } catch (NoSuchElementException healFail) {
                        // AI suggestion didn't work — try vision
                    }
                }
            } catch (Exception e) {
                // AI healing unavailable
            }

            // ── Phase 3: Vision healing (screenshot + multimodal LLM) ──
            try {
                String screenshotBase64 = ((org.openqa.selenium.TakesScreenshot) driver).getScreenshotAs(org.openqa.selenium.OutputType.BASE64);
                HealingClient.HealResult visionResult = client.resolveVision(selector, url, screenshotBase64, null);
                if (visionResult != null && visionResult.selector != null && !visionResult.selector.equals(selector)) {
                    System.out.println("[qabot-heal] Vision: \\"" + selector + "\\" → \\"" + visionResult.selector + "\\" " +
                        "(confidence: " + Math.round(visionResult.confidence * 100) + "%, strategy: visionHealing)");
                    try {
                        By healedBy = selectorToBy(visionResult.selector);
                        WebElement element = driver.findElement(healedBy);
                        int duration = (int)(System.currentTimeMillis() - start);
                        client.report(selectorKey, url, true, visionResult.selector, visionResult.confidence, "visionHealing", duration);
                        storeFingerprint(visionResult.selector, url, element);
                        healedCount++;
                        return element;
                    } catch (NoSuchElementException healFail) {
                        // Vision suggestion didn't work either
                    }
                }
            } catch (Exception e) {
                // Screenshot or vision healing unavailable
            }

            // All strategies exhausted — report failure and throw original error
            int duration = (int)(System.currentTimeMillis() - start);
            client.report(selectorKey, url, false, null, 0, null, duration);
            throw original;
        }
    }

    /**
     * Find multiple elements with self-healing (3-phase strategy chain).
     */
    public List<WebElement> findElements(By by) {
        String selector = byToSelector(by);
        String url = getCurrentUrl();
        String selectorKey = "css:" + selector;

        try {
            List<WebElement> elements = driver.findElements(by);
            if (!elements.isEmpty()) {
                storeFingerprint(selector, url, elements.get(0));
            }
            return elements;
        } catch (Exception original) {
            String errorMsg = original.getMessage();

            // ── Phase 1: Deterministic candidates ──
            HealingClient.HealResult result = client.resolve(selector, url, null, errorMsg);
            if (result != null && result.selector != null && !result.selector.equals(selector)) {
                java.util.List<HealingClient.HealCandidate> candidates = new java.util.ArrayList<>();
                HealingClient.HealCandidate best = new HealingClient.HealCandidate();
                best.selector = result.selector;
                best.strategy = result.strategy != null ? result.strategy : "fingerprint";
                candidates.add(best);
                if (result.candidates != null) {
                    for (HealingClient.HealCandidate c : result.candidates) {
                        if (c.selector != null && !c.selector.equals(selector) && !c.selector.equals(result.selector)) {
                            candidates.add(c);
                        }
                    }
                }

                for (HealingClient.HealCandidate candidate : candidates) {
                    try {
                        By healedBy = selectorToBy(candidate.selector);
                        List<WebElement> elements = driver.findElements(healedBy);
                        if (!elements.isEmpty()) {
                            client.report(selectorKey, url, true, candidate.selector, result.confidence, candidate.strategy, 0);
                            return elements;
                        }
                    } catch (Exception ignored) {
                    }
                }
            }

            // ── Phase 2: AI text-based healing ──
            try {
                HealingClient.HealResult aiResult = client.resolveAI(selector, url, errorMsg, null);
                if (aiResult != null && aiResult.selector != null && !aiResult.selector.equals(selector)) {
                    try {
                        By healedBy = selectorToBy(aiResult.selector);
                        List<WebElement> elements = driver.findElements(healedBy);
                        if (!elements.isEmpty()) {
                            client.report(selectorKey, url, true, aiResult.selector, aiResult.confidence, "aiHealing", 0);
                            return elements;
                        }
                    } catch (Exception ignored) {
                    }
                }
            } catch (Exception ignored) {
            }

            // ── Phase 3: Vision healing ──
            try {
                String screenshotBase64 = ((org.openqa.selenium.TakesScreenshot) driver).getScreenshotAs(org.openqa.selenium.OutputType.BASE64);
                HealingClient.HealResult visionResult = client.resolveVision(selector, url, screenshotBase64, null);
                if (visionResult != null && visionResult.selector != null && !visionResult.selector.equals(selector)) {
                    try {
                        By healedBy = selectorToBy(visionResult.selector);
                        List<WebElement> elements = driver.findElements(healedBy);
                        if (!elements.isEmpty()) {
                            client.report(selectorKey, url, true, visionResult.selector, visionResult.confidence, "visionHealing", 0);
                            return elements;
                        }
                    } catch (Exception ignored) {
                    }
                }
            } catch (Exception ignored) {
            }

            // All strategies exhausted
            client.report(selectorKey, url, false, null, 0, null, 0);
            throw original;
        }
    }

    /**
     * Click element with self-healing.
     */
    public void click(By by) {
        findElement(by).click();
    }

    /**
     * Send keys to element with self-healing.
     */
    public void sendKeys(By by, CharSequence... keys) {
        findElement(by).sendKeys(keys);
    }

    /**
     * Get text from element with self-healing.
     */
    public String getText(By by) {
        return findElement(by).getText();
    }

    private void storeFingerprint(String selector, String url, WebElement element) {
        try {
            JavascriptExecutor js = (JavascriptExecutor) driver;
            @SuppressWarnings("unchecked")
            java.util.Map<String, Object> fp = (java.util.Map<String, Object>) js.executeScript(
                "var el = arguments[0]; var rect = el.getBoundingClientRect(); " +
                "return { tagName: el.tagName.toLowerCase(), id: el.id || null, " +
                "testId: el.getAttribute('data-testid') || null, " +
                "className: el.className || null, " +
                "ariaLabel: el.getAttribute('aria-label') || null, " +
                "name: el.getAttribute('name') || null, " +
                "textContent: (el.textContent || '').trim().substring(0, 100) || null, " +
                "type: el.type || null, " +
                "boundingBox: {x: rect.x, y: rect.y, width: rect.width, height: rect.height} };",
                element);
            JsonObject fpJson = new Gson().toJsonTree(fp).getAsJsonObject();
            client.storeFingerprint("css:" + selector, url, fpJson);
        } catch (Exception ignored) {
        }
    }

    private String getCurrentUrl() {
        try {
            return driver.getCurrentUrl();
        } catch (Exception e) {
            return "appium://unknown";
        }
    }

    private String byToSelector(By by) {
        String str = by.toString();
        if (str.startsWith("By.id:")) return "#" + str.substring(7).trim();
        if (str.startsWith("By.cssSelector:")) return str.substring(16).trim();
        if (str.startsWith("By.className:")) return "." + str.substring(14).trim();
        if (str.startsWith("By.name:")) return "[name=\\"" + str.substring(9).trim() + "\\"]";
        return str;
    }

    private By selectorToBy(String selector) {
        if (selector.startsWith("#")) return By.id(selector.substring(1));
        if (selector.startsWith(".")) return By.className(selector.substring(1));
        if (selector.startsWith("//") || selector.startsWith("(//")) return By.xpath(selector);
        if (selector.startsWith("text=")) return By.linkText(selector.substring(5));
        if (selector.startsWith("[data-testid=")) return By.cssSelector(selector);
        return By.cssSelector(selector);
    }
}
`;

    return files;
  },

  getIntegrationInstructions(config: HealingAdapterConfig): string {
    return `
## Appium Self-Healing Integration (Java)

### Generated Files:
- src/test/java/healing/HealingClient.java — HTTP client for qabot healing API
- src/test/java/healing/HealingDriver.java — AppiumDriver wrapper with self-healing

### Dependencies (add to pom.xml):
\`\`\`xml
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.10.1</version>
</dependency>
\`\`\`

### Usage:
\`\`\`java
AppiumDriver driver = new AndroidDriver(url, caps);
HealingDriver healing = new HealingDriver(driver);

// Use healing methods instead of driver directly:
healing.click(By.id("login-btn"));
healing.sendKeys(By.cssSelector(".search"), "Hello");
String text = healing.getText(By.id("title"));

// Or find elements manually:
WebElement el = healing.findElement(By.id("submit"));
\`\`\`

### How It Works:
- On success: captures element fingerprints and stores them via qabot API
- On failure: requests healed selectors from qabot's healing engine
- Works with Android and iOS Appium drivers
- Dashboard: ${config.healingServerUrl}/healing
`.trim();
  },
};
