import type { HealingAdapter, HealingAdapterConfig } from './base.js';

/**
 * Cypress TypeScript healing adapter.
 *
 * Generates:
 * 1. cypress/support/healing-config.ts — Configuration
 * 2. cypress/support/healing-client.ts — HTTP client (Node-side via cy.task)
 * 3. cypress/support/healing-commands.ts — Custom command overrides
 * 4. cypress/plugins/healing-plugin.ts — Node event handler for cy.task
 */
export const cypressTsAdapter: HealingAdapter = {
  framework: 'cypress',
  language: 'typescript',
  displayName: 'Cypress (TypeScript)',

  generate(config: HealingAdapterConfig): Record<string, string> {
    const files: Record<string, string> = {};

    // ── healing-config.ts ─────────────────────────────────────────────
    files['cypress/support/healing-config.ts'] = `// qabot Self-Healing Configuration. Auto-generated by qabot.
export const HealingConfig = {
  HEALING_SERVER_URL: '${config.healingServerUrl}',
  CONFIDENCE_THRESHOLD: ${config.confidenceThreshold},
  AI_ENABLED: ${config.enableAIFallback},
  ENABLED: true,
  FRAMEWORK: 'cypress',
  LANGUAGE: 'typescript',
} as const;
`;

    // ── healing-client.ts ─────────────────────────────────────────────
    files['cypress/support/healing-client.ts'] = `// qabot Healing HTTP Client (Node-side). Auto-generated by qabot.
// Called via cy.task() from Cypress commands.
import { HealingConfig } from './healing-config';

interface HealResult {
  healed: boolean;
  selector?: string;
  selectorStrategy?: string;
  confidence?: number;
  strategy?: string;
  durationMs?: number;
}

export class HealingClient {
  private serverUrl: string;

  constructor(serverUrl?: string) {
    this.serverUrl = serverUrl || HealingConfig.HEALING_SERVER_URL;
  }

  async resolve(selector: string, pageUrl: string, errorMessage?: string): Promise<HealResult | null> {
    try {
      const res = await fetch(\`\${this.serverUrl}/api/heal/resolve\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          selector,
          selectorStrategy: 'css',
          pageUrl,
          framework: HealingConfig.FRAMEWORK,
          language: HealingConfig.LANGUAGE,
          errorMessage,
        }),
        signal: AbortSignal.timeout(5000),
      });
      if (res.ok) return await res.json();
    } catch { /* server not running */ }
    return null;
  }

  async storeFingerprint(selectorKey: string, url: string, fingerprint: Record<string, unknown>): Promise<void> {
    try {
      await fetch(\`\${this.serverUrl}/api/heal/fingerprint\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          selectorKey,
          url,
          fingerprint,
          framework: HealingConfig.FRAMEWORK,
        }),
        signal: AbortSignal.timeout(5000),
      });
    } catch { /* ignore */ }
  }

  async resolveAI(selector: string, pageUrl: string, errorMessage?: string, testContext?: { testName?: string; stepName?: string; scenarioName?: string; actionType?: string }): Promise<HealResult | null> {
    try {
      const res = await fetch(\`\${this.serverUrl}/api/heal/resolve\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          selector, selectorStrategy: 'css', pageUrl,
          framework: HealingConfig.FRAMEWORK, language: HealingConfig.LANGUAGE,
          errorMessage, requestAI: true, testContext,
        }),
        signal: AbortSignal.timeout(10000),
      });
      if (res.ok) { const data = await res.json(); return (data as HealResult).healed ? data as HealResult : null; }
    } catch { /* AI unavailable */ }
    return null;
  }

  async report(selectorKey: string, url: string, healed: boolean,
    healedSelector?: string, confidence?: number, strategy?: string): Promise<void> {
    try {
      await fetch(\`\${this.serverUrl}/api/heal/report\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          selectorKey, url, healed,
          healedSelector, confidence, strategy,
          framework: HealingConfig.FRAMEWORK,
          language: HealingConfig.LANGUAGE,
          originalSelector: selectorKey,
        }),
        signal: AbortSignal.timeout(5000),
      });
    } catch { /* ignore */ }
  }
}
`;

    // ── healing-plugin.ts ─────────────────────────────────────────────
    files['cypress/plugins/healing-plugin.ts'] = `// qabot Self-Healing Plugin (Node event handler). Auto-generated by qabot.
// Add to cypress.config.ts: setupNodeEvents(on, config) { healingPlugin(on, config); }
import { HealingClient } from '../support/healing-client';

const client = new HealingClient();

export function healingPlugin(
  on: Cypress.PluginEvents,
  _config: Cypress.PluginConfigOptions,
) {
  on('task', {
    async healSelector({ selector, pageUrl, errorMessage }: { selector: string; pageUrl: string; errorMessage?: string }) {
      const result = await client.resolve(selector, pageUrl, errorMessage);
      return result || null;
    },

    async healSelectorAI({ selector, pageUrl, errorMessage, testContext }: { selector: string; pageUrl: string; errorMessage?: string; testContext?: { testName?: string; stepName?: string; scenarioName?: string; actionType?: string } }) {
      const result = await client.resolveAI(selector, pageUrl, errorMessage, testContext);
      return result || null;
    },

    async storeFingerprint({ selectorKey, url, fingerprint }: {
      selectorKey: string; url: string; fingerprint: Record<string, unknown>;
    }) {
      await client.storeFingerprint(selectorKey, url, fingerprint);
      return null;
    },

    async reportHealing({ selectorKey, url, healed, healedSelector, confidence, strategy }: {
      selectorKey: string; url: string; healed: boolean;
      healedSelector?: string; confidence?: number; strategy?: string;
    }) {
      await client.report(selectorKey, url, healed, healedSelector, confidence, strategy);
      return null;
    },
  });
}
`;

    // ── healing-commands.ts ───────────────────────────────────────────
    files['cypress/support/healing-commands.ts'] = `// qabot Self-Healing Commands. Auto-generated by qabot.
// Import in cypress/support/e2e.ts: import './healing-commands';
import { HealingConfig } from './healing-config';

// Capture element fingerprint via DOM
function captureFingerprint($el: JQuery<HTMLElement>): Record<string, unknown> {
  const el = $el[0]!;
  const rect = el.getBoundingClientRect();
  return {
    tagName: el.tagName.toLowerCase(),
    id: el.id || null,
    testId: el.getAttribute('data-testid') || null,
    className: el.className || null,
    ariaLabel: el.getAttribute('aria-label') || null,
    ariaRole: el.getAttribute('role') || null,
    name: el.getAttribute('name') || null,
    placeholder: el.getAttribute('placeholder') || null,
    textContent: (el.textContent || '').trim().substring(0, 100) || null,
    href: (el as HTMLAnchorElement).href || null,
    type: (el as HTMLInputElement).type || null,
    boundingBox: { x: rect.x, y: rect.y, width: rect.width, height: rect.height },
    parentTag: el.parentElement ? el.parentElement.tagName.toLowerCase() : null,
    siblingIndex: el.parentElement ? Array.from(el.parentElement.children).indexOf(el) : -1,
    childCount: el.children.length,
  };
}

// Override cy.get to add self-healing
Cypress.Commands.overwrite('get', (originalFn, selector: string, options?: Partial<Cypress.Loggable & Cypress.Timeoutable & Cypress.Withinable & Cypress.Shadow>) => {
  if (!HealingConfig.ENABLED || typeof selector !== 'string') {
    return originalFn(selector, options);
  }

  return originalFn(selector, { ...options, timeout: 2000 }).then(
    ($el) => {
      // Success — store fingerprint as baseline
      const selectorKey = \`css:\${selector}\`;
      cy.url().then((url) => {
        const fp = captureFingerprint($el);
        cy.task('storeFingerprint', { selectorKey, url, fingerprint: fp }, { log: false });
      });
      return $el;
    },
    (_err) => {
      // Failed — try healing with multi-candidate + AI fallback
      const errMsg = _err instanceof Error ? _err.message : '';

      // Recursive function to try candidates one by one
      function tryCandidates(
        candidates: Array<{ selector: string; strategy: string }>,
        idx: number, pageUrl: string,
      ): Cypress.Chainable {
        if (idx >= candidates.length) {
          // All deterministic candidates exhausted — try AI
          const testContext = { testName: Cypress.currentTest?.title };
          return cy.task('healSelectorAI', { selector, pageUrl, errorMessage: errMsg, testContext }, { log: false }).then((aiResult: any) => {
            if (aiResult && aiResult.healed && aiResult.selector && aiResult.selector !== selector) {
              Cypress.log({ name: 'qabot-heal', message: \`AI: "\${selector}" → "\${aiResult.selector}"\` });
              return originalFn(aiResult.selector, { ...options, timeout: 3000 }).then(($el) => {
                cy.task('reportHealing', {
                  selectorKey: \`css:\${selector}\`, url: pageUrl, healed: true,
                  healedSelector: aiResult.selector, confidence: aiResult.confidence, strategy: 'aiHealing',
                }, { log: false });
                return $el;
              }, () => {
                cy.task('reportHealing', { selectorKey: \`css:\${selector}\`, url: pageUrl, healed: false }, { log: false });
                return originalFn(selector, options); // final fallback — original error
              });
            }
            cy.task('reportHealing', { selectorKey: \`css:\${selector}\`, url: pageUrl, healed: false }, { log: false });
            return originalFn(selector, options);
          });
        }
        const cand = candidates[idx]!;
        const label = idx === 0 ? 'Trying' : 'Fallback';
        Cypress.log({ name: 'qabot-heal', message: \`\${label}: "\${selector}" → "\${cand.selector}" (strategy: \${cand.strategy})\` });
        return originalFn(cand.selector, { ...options, timeout: 3000 }).then(
          ($el) => {
            cy.task('reportHealing', {
              selectorKey: \`css:\${selector}\`, url: pageUrl, healed: true,
              healedSelector: cand.selector, confidence: 0.8, strategy: cand.strategy,
            }, { log: false });
            return $el;
          },
          () => tryCandidates(candidates, idx + 1, pageUrl),
        );
      }

      cy.url().then((pageUrl) => {
        cy.task('healSelector', { selector, pageUrl, errorMessage: errMsg }, { log: false }).then((result: any) => {
          if (result && result.healed && result.selector && result.selector !== selector) {
            // Build candidate list
            const candidates: Array<{ selector: string; strategy: string }> = [
              { selector: result.selector, strategy: result.strategy || 'fingerprint' },
            ];
            if (result.candidates) {
              for (const c of result.candidates) {
                if (c.selector !== selector && c.selector !== result.selector) candidates.push(c);
              }
            }
            return tryCandidates(candidates, 0, pageUrl);
          }
          // No candidates — try AI directly
          return tryCandidates([], 0, pageUrl);
        });
      });
    },
  );
});
`;

    return files;
  },

  getIntegrationInstructions(config: HealingAdapterConfig): string {
    return `
## Cypress Self-Healing Integration

### Generated Files:
- cypress/support/healing-config.ts — Configuration
- cypress/support/healing-client.ts — HTTP client (Node-side)
- cypress/support/healing-commands.ts — Custom command overrides
- cypress/plugins/healing-plugin.ts — Node event handler

### Setup:
1. Start qabot UI server: \`qabot /buildUI\` or \`qabot\` then \`/ui\`

2. Register the plugin in \`cypress.config.ts\`:
   \`\`\`typescript
   import { healingPlugin } from './cypress/plugins/healing-plugin';

   export default defineConfig({
     e2e: {
       setupNodeEvents(on, config) {
         healingPlugin(on, config);
       },
     },
   });
   \`\`\`

3. Import commands in \`cypress/support/e2e.ts\`:
   \`\`\`typescript
   import './healing-commands';
   \`\`\`

4. All \`cy.get()\` calls will now auto-heal on failure
5. View healing stats at ${config.healingServerUrl}/healing
`.trim();
  },
};
