import type { HealingAdapter, HealingAdapterConfig } from './base.js';

/**
 * Playwright Python healing adapter.
 *
 * Generates:
 * 1. tests/helpers/healing_client.py — HTTP client for qabot healing API
 * 2. tests/conftest.py — pytest fixture with self-healing page
 */
export const playwrightPythonAdapter: HealingAdapter = {
  framework: 'playwright',
  language: 'python',
  displayName: 'Playwright (Python)',

  generate(config: HealingAdapterConfig): Record<string, string> {
    const files: Record<string, string> = {};

    // ── Healing Client ─────────────────────────────────────────────────────
    files['tests/helpers/healing_client.py'] = `"""
qabot Healing Client — HTTP bridge to qabot's self-healing API.
Auto-generated by qabot. Do not edit manually.
"""

import json
import urllib.request
import urllib.error
from typing import Optional, Dict, Any

HEALING_SERVER = "${config.healingServerUrl}"
CONFIDENCE_THRESHOLD = ${config.confidenceThreshold}
FRAMEWORK = "playwright"
LANGUAGE = "python"


class HealingClient:
    """HTTP client for the qabot healing API."""

    def __init__(self, server_url: str = HEALING_SERVER):
        self.server_url = server_url

    def _post(self, path: str, data: dict) -> Optional[dict]:
        """Make a POST request to the healing API."""
        try:
            req = urllib.request.Request(
                f"{self.server_url}{path}",
                data=json.dumps(data).encode("utf-8"),
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=10) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except (urllib.error.URLError, json.JSONDecodeError, OSError):
            return None

    def store_fingerprint(self, selector_key: str, url: str, fingerprint: Dict[str, Any]) -> None:
        """Store element fingerprint for baseline."""
        self._post("/api/heal/fingerprint", {
            "selectorKey": selector_key,
            "url": url,
            "fingerprint": fingerprint,
            "framework": FRAMEWORK,
        })

    def resolve(self, selector: str, page_url: str, fingerprint: Optional[Dict] = None, error_message: Optional[str] = None) -> Optional[dict]:
        """Request a healed selector from qabot API."""
        data = {
            "selector": selector,
            "selectorStrategy": "css",
            "pageUrl": page_url,
            "framework": FRAMEWORK,
            "language": LANGUAGE,
        }
        if fingerprint:
            data["fingerprint"] = fingerprint
        if error_message:
            data["errorMessage"] = error_message
        result = self._post("/api/heal/resolve", data)
        if result and result.get("healed") and result.get("confidence", 0) >= CONFIDENCE_THRESHOLD:
            return result
        return None

    def resolve_ai(self, selector: str, page_url: str, error_message: Optional[str] = None,
                   test_context: Optional[Dict[str, Any]] = None) -> Optional[dict]:
        """Request AI-based healing (LLM fallback)."""
        try:
            body: Dict[str, Any] = {
                "selector": selector,
                "selectorStrategy": "css",
                "pageUrl": page_url,
                "framework": FRAMEWORK,
                "language": LANGUAGE,
                "errorMessage": error_message,
                "requestAI": True,
            }
            if test_context:
                body["testContext"] = test_context
            result = self._post("/api/heal/resolve", body)
            if result and result.get("healed") and result.get("selector"):
                return result
            return None
        except Exception:
            return None

    def resolve_vision(self, selector: str, page_url: str, screenshot_base64: str,
                       test_context: Optional[Dict[str, Any]] = None) -> Optional[dict]:
        """Request vision-based healing (screenshot + multimodal LLM)."""
        try:
            body: Dict[str, Any] = {
                "selector": selector,
                "pageUrl": page_url,
                "screenshotBase64": screenshot_base64,
                "framework": FRAMEWORK,
                "language": LANGUAGE,
            }
            if test_context:
                body["errorMessage"] = test_context.get("errorMessage")
                body["testContext"] = test_context
            req = urllib.request.Request(
                f"{self.server_url}/api/heal/vision",
                data=json.dumps(body).encode("utf-8"),
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                if data.get("healed") and data.get("selector"):
                    return data
            return None
        except (urllib.error.URLError, json.JSONDecodeError, OSError):
            return None

    def report(self, selector_key: str, url: str, healed: bool,
               healed_selector: Optional[str] = None, confidence: float = 0,
               strategy: Optional[str] = None, duration_ms: int = 0) -> None:
        """Report healing outcome."""
        self._post("/api/heal/report", {
            "selectorKey": selector_key,
            "url": url,
            "healed": healed,
            "healedSelector": healed_selector,
            "confidence": confidence,
            "strategy": strategy,
            "framework": FRAMEWORK,
            "language": LANGUAGE,
            "originalSelector": selector_key,
            "durationMs": duration_ms,
        })


def capture_fingerprint(page, selector: str) -> Optional[Dict[str, Any]]:
    """Capture an element's fingerprint using page.evaluate() + querySelector.

    Uses document.querySelector() inside page.evaluate() — runs directly in
    the browser DOM. querySelector naturally returns the FIRST matching element,
    so it never throws strict mode violations for multi-match selectors.

    CSS selectors only. Playwright-specific selectors (text=, role=) return None.
    """
    try:
        return page.evaluate("""(sel) => {
            const el = document.querySelector(sel);
            if (!el) return null;
            const rect = el.getBoundingClientRect();
            return {
                tagName: el.tagName.toLowerCase(),
                id: el.id || null,
                testId: el.getAttribute('data-testid') || null,
                className: el.className || null,
                ariaLabel: el.getAttribute('aria-label') || null,
                name: el.getAttribute('name') || null,
                placeholder: el.getAttribute('placeholder') || null,
                textContent: (el.textContent || '').trim().substring(0, 100) || null,
                type: el.type || null,
                boundingBox: {x: rect.x, y: rect.y, width: rect.width, height: rect.height}
            };
        }""", selector)
    except Exception:
        return None
`;

    // ── Pytest conftest fixture ─────────────────────────────────────────────
    files['tests/helpers/healing_conftest.py'] = `"""
qabot Self-Healing pytest Fixture for Playwright Python.
Auto-generated by qabot. Do not edit manually.

Usage:
  Add to your conftest.py:
    from tests.helpers.healing_conftest import healing_page

  Then use healing_page fixture in tests:
    def test_login(healing_page):
        healing_page.goto("https://example.com")
        healing_page.locator("#login").click()
"""

import base64
import pytest
import time
from typing import Generator
from playwright.sync_api import Page
from .healing_client import HealingClient, capture_fingerprint

_client = HealingClient()


def _wrap_locator_with_healing(page: Page) -> Page:
    """Wrap page.locator() to add self-healing on element-not-found failures."""
    original_locator = page.locator

    def healing_locator(selector: str, **kwargs):
        loc = original_locator(selector, **kwargs)

        # List of methods to wrap
        methods_to_wrap = [
            "click", "dblclick", "fill", "type", "check", "uncheck",
            "select_option", "hover", "focus", "press", "scroll_into_view_if_needed",
            "wait_for", "tap", "set_input_files", "clear", "input_value",
            "text_content", "inner_text", "inner_html", "get_attribute",
            "is_visible", "is_enabled", "is_checked", "is_disabled", "is_editable",
        ]

        for method_name in methods_to_wrap:
            original_method = getattr(loc, method_name, None)
            if original_method is None or not callable(original_method):
                continue

            def make_wrapper(orig, mname):
                def wrapper(*args, **kw):
                    try:
                        result = orig(*args, **kw)
                        # Success — capture fingerprint
                        try:
                            fp = capture_fingerprint(page, selector)
                            if fp:
                                _client.store_fingerprint(f"css:{selector}", page.url, fp)
                        except Exception:
                            pass
                        return result
                    except Exception as original_error:
                        # 3-phase healing strategy chain
                        selector_key = f"css:{selector}"
                        start = time.time()
                        err_msg = str(original_error)

                        # Phase 1: Deterministic candidates (fingerprint, similarSelector, textMatch, ancestorSearch)
                        heal_result = _client.resolve(selector, page.url, error_message=err_msg)
                        if heal_result and heal_result.get("selector") and heal_result["selector"] != selector:
                            candidates = [{"selector": heal_result["selector"], "strategy": heal_result.get("strategy", "fingerprint")}]
                            for c in heal_result.get("candidates", []):
                                if c["selector"] != selector and c["selector"] != heal_result["selector"]:
                                    candidates.append(c)

                            for i, candidate in enumerate(candidates):
                                label = "Trying" if i == 0 else "Fallback"
                                print(f"[qabot-heal] {label}: '{selector}' -> '{candidate['selector']}' "
                                      f"(strategy: {candidate['strategy']}"
                                      f"{f', attempt {i+1}/{len(candidates)}' if i > 0 else ''})")
                                try:
                                    healed_loc = original_locator(candidate["selector"], **kwargs)
                                    result = getattr(healed_loc, mname)(*args, **kw)
                                    duration = int((time.time() - start) * 1000)
                                    _client.report(selector_key, page.url, True,
                                                   candidate["selector"], heal_result.get("confidence", 0),
                                                   candidate["strategy"], duration)
                                    return result
                                except Exception:
                                    pass  # try next candidate

                        # Build test context for AI/vision healing
                        test_context = {
                            "actionType": mname,
                            "errorMessage": err_msg,
                            "framework": "playwright",
                            "language": "python",
                        }

                        # Phase 2: AI text-based healing (LLM fallback)
                        try:
                            ai_result = _client.resolve_ai(selector, page.url, err_msg, test_context=test_context)
                            if ai_result and ai_result.get("selector") and ai_result["selector"] != selector:
                                print(f"[qabot-heal] AI: '{selector}' -> '{ai_result['selector']}' "
                                      f"(confidence: {ai_result.get('confidence', 0):.0%}, strategy: aiHealing)")
                                try:
                                    ai_loc = original_locator(ai_result["selector"], **kwargs)
                                    result = getattr(ai_loc, mname)(*args, **kw)
                                    duration = int((time.time() - start) * 1000)
                                    _client.report(selector_key, page.url, True,
                                                   ai_result["selector"], ai_result.get("confidence", 0),
                                                   "aiHealing", duration)
                                    return result
                                except Exception:
                                    pass  # AI suggestion didn't work
                        except Exception:
                            pass  # AI healing unavailable

                        # Phase 3: Vision healing (screenshot + multimodal LLM)
                        try:
                            screenshot_bytes = page.screenshot(type="png")
                            b64 = base64.b64encode(screenshot_bytes).decode("utf-8")
                            vision_result = _client.resolve_vision(selector, page.url, b64, test_context=test_context)
                            if vision_result and vision_result.get("selector") and vision_result["selector"] != selector:
                                print(f"[qabot-heal] Vision: '{selector}' -> '{vision_result['selector']}' "
                                      f"(confidence: {vision_result.get('confidence', 0):.0%}, strategy: visionHealing)")
                                try:
                                    vision_loc = original_locator(vision_result["selector"], **kwargs)
                                    result = getattr(vision_loc, mname)(*args, **kw)
                                    duration = int((time.time() - start) * 1000)
                                    _client.report(selector_key, page.url, True,
                                                   vision_result["selector"], vision_result.get("confidence", 0),
                                                   "visionHealing", duration)
                                    return result
                                except Exception:
                                    pass  # Vision suggestion didn't work
                        except Exception:
                            pass  # Screenshot or vision healing unavailable

                        # All strategies exhausted
                        duration = int((time.time() - start) * 1000)
                        _client.report(selector_key, page.url, False, duration_ms=duration)
                        raise original_error
                return wrapper
            setattr(loc, method_name, make_wrapper(original_method, method_name))

        return loc

    page.locator = healing_locator
    return page


@pytest.fixture
def healing_page(page: Page) -> Generator[Page, None, None]:
    """Pytest fixture that wraps Playwright page with self-healing locators."""
    healed_page = _wrap_locator_with_healing(page)
    yield healed_page
`;

    return files;
  },

  getIntegrationInstructions(config: HealingAdapterConfig): string {
    return `
## Playwright Python Self-Healing Integration

### Generated Files:
- tests/helpers/healing_client.py — HTTP client for qabot healing API
- tests/helpers/healing_conftest.py — pytest fixture with self-healing page

### Setup:
1. Start qabot UI server: \`qabot /buildUI\`
2. Add to your conftest.py:

   \`\`\`python
   from tests.helpers.healing_conftest import healing_page  # noqa: F401
   \`\`\`

3. Use \`healing_page\` fixture instead of \`page\`:

   \`\`\`python
   # Before:
   def test_login(page):
       page.goto("https://example.com")

   # After:
   def test_login(healing_page):
       healing_page.goto("https://example.com")
   \`\`\`

4. Run tests: \`pytest --headed\`

### How It Works:
- On success: captures element fingerprints and stores them via qabot API
- On failure: requests healed selectors from qabot's healing engine
- Logs: [qabot-heal] Healed: 'old' → 'new' (confidence: 90%, strategy: fingerprint)
- Dashboard: ${config.healingServerUrl}/healing
`.trim();
  },
};
