import type { HealingAdapter, HealingAdapterConfig } from './base.js';

/**
 * Playwright TypeScript/JavaScript healing adapter.
 *
 * Generates:
 * 1. tests/helpers/healing-client.ts — HTTP client for qabot healing API
 * 2. tests/fixtures/healing.ts — Custom fixture that overrides `page` with healing
 *
 * Zero-config: tests only change one import line. Uses `page` as normal.
 * Full parity with the Cucumber adapter: HEAL/PROBE split, upgradeLocator,
 * selector cache, chain propagation, fingerprint deduplication.
 */
export const playwrightTsAdapter: HealingAdapter = {
  framework: 'playwright',
  language: 'typescript',
  displayName: 'Playwright (TypeScript/JavaScript)',

  generate(config: HealingAdapterConfig): Record<string, string> {
    const files: Record<string, string> = {};

    // ── Healing Client ─────────────────────────────────────────────────────
    files['tests/helpers/healing-client.ts'] = `/**
 * qabot Healing Client — HTTP bridge to qabot's self-healing API.
 * Auto-generated by qabot. Do not edit manually.
 */

const HEALING_SERVER = '${config.healingServerUrl}';
const CONFIDENCE_THRESHOLD = ${config.confidenceThreshold};

export interface ElementFingerprint {
  tagName: string;
  id?: string;
  testId?: string;
  className?: string;
  ariaLabel?: string;
  ariaRole?: string;
  name?: string;
  placeholder?: string;
  textContent?: string;
  href?: string;
  type?: string;
  boundingBox?: { x: number; y: number; width: number; height: number };
  parentTag?: string;
  siblingIndex?: number;
  childCount?: number;
}

export interface HealResult {
  healed: boolean;
  selector?: string;
  selectorStrategy?: string;
  confidence: number;
  strategy?: string;
  durationMs: number;
  candidates?: Array<{ selector: string; strategy: string }>;
}

export class HealingClient {
  private serverUrl: string;

  constructor(serverUrl: string = HEALING_SERVER) {
    this.serverUrl = serverUrl;
  }

  async storeFingerprint(selectorKey: string, url: string, fingerprint: ElementFingerprint): Promise<void> {
    try {
      await fetch(\`\${this.serverUrl}/api/heal/fingerprint\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ selectorKey, url, fingerprint, framework: 'playwright' }),
      });
    } catch {
      // qabot server not running — continue silently
    }
  }

  async resolve(selector: string, pageUrl: string, fingerprint?: ElementFingerprint, errorMessage?: string): Promise<HealResult | null> {
    try {
      const resp = await fetch(\`\${this.serverUrl}/api/heal/resolve\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          selector,
          selectorStrategy: 'css',
          fingerprint,
          pageUrl,
          framework: 'playwright',
          language: 'typescript',
          errorMessage,
        }),
      });
      if (!resp.ok) return null;
      const data = await resp.json() as HealResult;
      return data.healed ? data : null;
    } catch {
      return null;
    }
  }

  async resolveAI(selector: string, pageUrl: string, errorMessage?: string, testContext?: { testName?: string; stepName?: string; scenarioName?: string; actionType?: string }): Promise<HealResult | null> {
    try {
      const resp = await fetch(\`\${this.serverUrl}/api/heal/resolve\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ selector, selectorStrategy: 'css', pageUrl, framework: 'playwright', language: 'typescript', errorMessage, requestAI: true, testContext }),
      });
      if (!resp.ok) return null;
      const data = await resp.json() as HealResult;
      return data.healed && data.selector ? data : null;
    } catch { return null; }
  }

  async resolveVision(selector: string, pageUrl: string, screenshotBase64: string, testContext?: { testName?: string; stepName?: string; scenarioName?: string; actionType?: string; errorMessage?: string }): Promise<HealResult | null> {
    try {
      const resp = await fetch(\`\${this.serverUrl}/api/heal/vision\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ selector, pageUrl, screenshotBase64, framework: 'playwright', language: 'typescript', errorMessage: testContext?.errorMessage, testContext }),
      });
      if (!resp.ok) return null;
      const data = await resp.json() as HealResult;
      return data.healed && data.selector ? data : null;
    } catch { return null; }
  }

  async report(selectorKey: string, url: string, healed: boolean, healedSelector?: string, confidence?: number, strategy?: string): Promise<void> {
    try {
      await fetch(\`\${this.serverUrl}/api/heal/report\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          selectorKey,
          url,
          healed,
          healedSelector,
          confidence,
          strategy,
          framework: 'playwright',
          language: 'typescript',
          originalSelector: selectorKey,
        }),
      });
    } catch {
      // Silently ignore
    }
  }
}

/**
 * Capture an element's fingerprint for self-healing baseline storage.
 *
 * Uses page.evaluate() with document.querySelector() — runs directly in the
 * browser DOM. querySelector naturally returns the FIRST matching element, so
 * it never throws strict mode violations for multi-match selectors.
 *
 * IMPORTANT: The selector is embedded directly into the expression string via
 * JSON.stringify() (IIFE pattern) rather than passed as a separate argument.
 * When page.evaluate() receives a STRING function, Playwright does not reliably
 * pass the second argument to the browser context — the arg is silently lost
 * and querySelector receives undefined, always returning null.
 *
 * Limitation: CSS selectors only. Playwright-specific selectors (text=, role=,
 * :has-text) return null. Acceptable because page.locator() overwhelmingly
 * uses CSS; getByText/getByRole use different APIs not wrapped here.
 */
export async function captureFingerprint(
  page: import('@playwright/test').Page,
  selector: string,
): Promise<ElementFingerprint | null> {
  try {
    return await page.evaluate(\`(() => {
      const el = document.querySelector(\${JSON.stringify(selector)});
      if (!el) return null;
      const rect = el.getBoundingClientRect();
      return {
        tagName: el.tagName.toLowerCase(),
        id: el.id || undefined,
        testId: el.getAttribute('data-testid') || undefined,
        className: el.className || undefined,
        ariaLabel: el.getAttribute('aria-label') || undefined,
        ariaRole: el.getAttribute('role') || undefined,
        name: el.getAttribute('name') || undefined,
        placeholder: el.getAttribute('placeholder') || undefined,
        textContent: (el.textContent || '').trim().slice(0, 100) || undefined,
        href: el.href || undefined,
        type: el.type || undefined,
        boundingBox: { x: rect.x, y: rect.y, width: rect.width, height: rect.height },
        parentTag: el.parentElement ? el.parentElement.tagName.toLowerCase() : undefined,
        siblingIndex: el.parentElement ? Array.from(el.parentElement.children).indexOf(el) : undefined,
        childCount: el.children.length,
      };
    })()\`) as ElementFingerprint | null;
  } catch {
    return null;
  }
}

/**
 * Capture fingerprint using a Playwright locator directly (fallback for getBy* selectors).
 *
 * document.querySelector() cannot resolve Playwright-specific selectors like
 * getByText, getByRole, getByLabel etc. This function uses the locator's own
 * .evaluate() method to extract DOM attributes from the matched element.
 * Called when captureFingerprint() returns null for non-CSS selectors.
 */
export async function captureFingerprintFromLocator(
  locator: any,
): Promise<ElementFingerprint | null> {
  try {
    return await locator.first().evaluate((el: Element) => {
      const rect = el.getBoundingClientRect();
      return {
        tagName: el.tagName.toLowerCase(),
        id: el.getAttribute('id') || undefined,
        testId: el.getAttribute('data-testid') || undefined,
        className: el.getAttribute('class') || undefined,
        ariaLabel: el.getAttribute('aria-label') || undefined,
        ariaRole: el.getAttribute('role') || undefined,
        name: el.getAttribute('name') || undefined,
        placeholder: el.getAttribute('placeholder') || undefined,
        textContent: (el.textContent || '').trim().slice(0, 100) || undefined,
        href: el.getAttribute('href') || undefined,
        type: el.getAttribute('type') || undefined,
        boundingBox: rect.width > 0 ? { x: Math.round(rect.x), y: Math.round(rect.y), width: Math.round(rect.width), height: Math.round(rect.height) } : undefined,
        parentTag: el.parentElement ? el.parentElement.tagName.toLowerCase() : undefined,
        siblingIndex: el.parentElement ? Array.from(el.parentElement.children).indexOf(el) : undefined,
        childCount: el.children.length,
      };
    }) as ElementFingerprint | null;
  } catch {
    return null;
  }
}
`;

    // ── Healing Fixture ────────────────────────────────────────────────────
    files['tests/fixtures/healing.ts'] = `/**
 * qabot Self-Healing Playwright Fixture.
 * Auto-generated by qabot. Do not edit manually.
 *
 * Usage — only change the import, everything else stays the same:
 *
 *   // Before:
 *   import { test, expect } from '@playwright/test';
 *
 *   // After:
 *   import { test, expect } from './fixtures/healing';
 *
 *   test('my test', async ({ page }) => {
 *     // page is automatically wrapped with healing — no other changes needed
 *   });
 */
import { test as base, type Page } from '@playwright/test';
import { HealingClient, captureFingerprint, captureFingerprintFromLocator, type ElementFingerprint } from '../helpers/healing-client';

const HEALING_SERVER = '${config.healingServerUrl}';
const client = new HealingClient();
const healingLog: Array<{ selector: string; healed: string; confidence: number; strategy: string }> = [];
let healingStatusLogged = false;

// Interaction methods: throw on element-not-found → healing is appropriate
const HEAL_METHODS = [
  'click', 'dblclick', 'fill', 'type', 'check', 'uncheck', 'selectOption',
  'hover', 'focus', 'press', 'scrollIntoViewIfNeeded', 'waitFor', 'tap',
  'setInputFiles', 'selectText', 'clear', 'inputValue', 'textContent',
  'innerText', 'innerHTML', 'getAttribute',
];

// State-probe methods: return boolean/number (no throw) → fingerprint-only, no healing
// count() returns a number — truthy (>0) triggers fingerprint capture, same as boolean probes
const PROBE_METHODS = [
  'isVisible', 'isEnabled', 'isChecked', 'isDisabled', 'isEditable', 'isHidden', 'count',
];

// Chain methods that return sub-locators
const CHAIN_METHODS = ['first', 'last', 'nth', 'filter', 'locator'];

/**
 * Upgrade a locator in-place: rebind ALL methods to the healed locator.
 * CRITICAL: Must include PROBE_METHODS — FallbackLocator patterns call
 * waitFor() then isVisible(). Without rebinding probes, isVisible still
 * operates on the broken selector and returns false.
 */
function upgradeLocator(loc: any, healedLoc: any): void {
  for (const m of [...HEAL_METHODS, ...PROBE_METHODS, ...CHAIN_METHODS]) {
    if (typeof healedLoc[m] === 'function') {
      loc[m] = healedLoc[m].bind(healedLoc);
    }
  }
}

function wrapLocatorActions(
  loc: any,
  selector: string,
  originalLocator: (...args: any[]) => any,
  page: Page,
  selectorCache: Map<string, string>,
  fingerprintedSelectors: Set<string>,
  pendingReports: Array<Promise<void>>,
): void {
  if (loc.__qabotWrapped) return;
  loc.__qabotWrapped = true;

  // ── HEAL_METHODS: wrap with self-healing on element-not-found ──
  for (const methodName of HEAL_METHODS) {
    const original = loc[methodName]?.bind(loc);
    if (typeof original !== 'function') continue;

    loc[methodName] = async (...args: any[]) => {
      let preCapture: ElementFingerprint | null = null;
      let preCaptureUrl = '';
      if (!fingerprintedSelectors.has(selector)) {
        preCaptureUrl = page.url();
        preCapture = await captureFingerprint(page, selector).catch(() => null);
        // Fallback: for getBy* selectors, querySelector can't resolve them.
        // Use the locator's own evaluate() to extract the fingerprint directly.
        if (!preCapture) {
          preCapture = await captureFingerprintFromLocator(loc).catch(() => null);
        }
      }

      try {
        const result = await original(...args);
        if (preCapture && !fingerprintedSelectors.has(selector)) {
          fingerprintedSelectors.add(selector);
          const fpKey = selector.startsWith('getBy') ? selector : \`css:\${selector}\`;
          pendingReports.push(client.storeFingerprint(fpKey, preCaptureUrl, preCapture).catch(() => {}));
        }
        return result;
      } catch (error) {
        const errMsg = error instanceof Error ? error.message : '';

        // Strict mode: auto-disambiguate with .first()
        if (errMsg.includes('strict mode violation')) {
          try {
            const firstLoc = loc.first();
            const result = await (firstLoc as any)[methodName](...args);
            console.log(
              \`[qabot-heal] Strict mode: "\${selector}" matched multiple elements. \` +
              \`Auto-disambiguated with .first().\`
            );
            if (!fingerprintedSelectors.has(selector)) {
              let fp = await captureFingerprint(page, selector).catch(() => null);
              if (!fp) fp = await captureFingerprintFromLocator(loc).catch(() => null);
              if (fp) {
                fingerprintedSelectors.add(selector);
                const fpKey = selector.startsWith('getBy') ? selector : \`css:\${selector}\`;
                pendingReports.push(client.storeFingerprint(fpKey, page.url(), fp).catch(() => {}));
              }
            }
            return result;
          } catch {
            throw error;
          }
        }

        // Only heal when the element wasn't found / doesn't match.
        // Skip healing for errors where the element WAS found but action failed
        // for other reasons (popup overlay blocking clicks, navigation timeout, etc.)
        const isElementNotFound =
          errMsg.includes('waiting for locator') ||
          errMsg.includes('resolved to 0 elements') ||
          errMsg.includes('no element matches') ||
          errMsg.includes('Element is not') ||
          errMsg.includes('element is not') ||
          errMsg.includes('not attached') ||
          errMsg.includes('Target closed') ||
          errMsg.includes('frame was detached');
        const isInterception =
          errMsg.includes('intercepts pointer events') ||
          errMsg.includes('element is outside of the viewport');

        if (isInterception || (!isElementNotFound && errMsg.includes('Timeout'))) {
          // Element exists but action can't reach it — healing won't help
          throw error;
        }

        // Element not found — 3-phase healing
        const selectorKey = selector.startsWith('getBy') ? selector : \`css:\${selector}\`;
        const testContext = { actionType: methodName };

        // Phase 1: Deterministic candidates
        const healResult = await client.resolve(selector, page.url(), undefined, errMsg);
        if (healResult && healResult.selector && healResult.selector !== selector) {
          const candidates: Array<{ selector: string; strategy: string }> = [
            { selector: healResult.selector, strategy: healResult.strategy || 'fingerprint' },
          ];
          if (healResult.candidates) {
            for (const c of healResult.candidates) {
              if (c.selector !== selector && c.selector !== healResult.selector) candidates.push(c);
            }
          }
          for (let i = 0; i < candidates.length; i++) {
            const cand = candidates[i]!;
            console.log(
              \`[qabot-heal] \${i === 0 ? 'Trying' : 'Fallback'}: "\\x1b[31m\${selector}\\x1b[0m" \` +
              \`-> "\\x1b[32m\${cand.selector}\\x1b[0m" (strategy: \${cand.strategy})\`
            );
            const healedLoc = originalLocator(cand.selector);
            try {
              const result = await healedLoc[methodName](...args);
              healingLog.push({ selector, healed: cand.selector, confidence: healResult.confidence, strategy: cand.strategy });
              upgradeLocator(loc, healedLoc);
              selectorCache.set(selector, cand.selector);
              pendingReports.push(client.report(selectorKey, page.url(), true, cand.selector, healResult.confidence, cand.strategy).catch(() => {}));
              return result;
            } catch { /* try next */ }
          }
        }

        // Phase 2: AI text-based healing
        try {
          const aiResult = await client.resolveAI(selector, page.url(), errMsg, testContext);
          if (aiResult && aiResult.selector && aiResult.selector !== selector) {
            console.log(
              \`[qabot-heal] AI: "\\x1b[31m\${selector}\\x1b[0m" -> "\\x1b[35m\${aiResult.selector}\\x1b[0m" \` +
              \`(confidence: \${Math.round(aiResult.confidence * 100)}%, strategy: aiHealing)\`
            );
            const aiLoc = originalLocator(aiResult.selector);
            try {
              const result = await aiLoc[methodName](...args);
              healingLog.push({ selector, healed: aiResult.selector, confidence: aiResult.confidence, strategy: 'aiHealing' });
              upgradeLocator(loc, aiLoc);
              selectorCache.set(selector, aiResult.selector);
              pendingReports.push(client.report(selectorKey, page.url(), true, aiResult.selector, aiResult.confidence, 'aiHealing').catch(() => {}));
              return result;
            } catch { /* try vision */ }
          }
        } catch { /* AI unavailable */ }

        // Phase 3: Vision healing
        try {
          const screenshotBuf = await page.screenshot({ type: 'png' });
          const screenshotBase64 = screenshotBuf.toString('base64');
          const visionResult = await client.resolveVision(selector, page.url(), screenshotBase64, { ...testContext, errorMessage: errMsg });
          if (visionResult && visionResult.selector && visionResult.selector !== selector) {
            console.log(
              \`[qabot-heal] Vision: "\\x1b[31m\${selector}\\x1b[0m" -> "\\x1b[36m\${visionResult.selector}\\x1b[0m" \` +
              \`(confidence: \${Math.round(visionResult.confidence * 100)}%, strategy: visionHealing)\`
            );
            const visionLoc = originalLocator(visionResult.selector);
            try {
              const result = await visionLoc[methodName](...args);
              healingLog.push({ selector, healed: visionResult.selector, confidence: visionResult.confidence, strategy: 'visionHealing' });
              upgradeLocator(loc, visionLoc);
              selectorCache.set(selector, visionResult.selector);
              pendingReports.push(client.report(selectorKey, page.url(), true, visionResult.selector, visionResult.confidence, 'visionHealing').catch(() => {}));
              return result;
            } catch { /* vision failed too */ }
          }
        } catch { /* screenshot/vision unavailable */ }

        pendingReports.push(client.report(selectorKey, page.url(), false).catch(() => {}));
        throw error;
      }
    };
  }

  // ── PROBE_METHODS: fingerprint-only on truthy result, no healing ──
  for (const methodName of PROBE_METHODS) {
    const original = loc[methodName]?.bind(loc);
    if (typeof original !== 'function') continue;

    loc[methodName] = async (...args: any[]) => {
      const result = await original(...args);
      if (result && !fingerprintedSelectors.has(selector)) {
        const currentUrl = page.url();
        let fp = await captureFingerprint(page, selector).catch(() => null);
        if (!fp) fp = await captureFingerprintFromLocator(loc).catch(() => null);
        if (fp) {
          fingerprintedSelectors.add(selector);
          const fpKey = selector.startsWith('getBy') ? selector : \`css:\${selector}\`;
          pendingReports.push(client.storeFingerprint(fpKey, currentUrl, fp).catch(() => {}));
        }
      }
      return result;
    };
  }

  // ── Propagate healing through .first() / .last() chains ──
  for (const sub of ['first', 'last'] as const) {
    const origSub = loc[sub]?.bind(loc);
    if (typeof origSub !== 'function') continue;
    loc[sub] = () => {
      const subLoc = origSub();
      const chainedFactory = (sel: string) => originalLocator(sel)[sub]();
      wrapLocatorActions(subLoc, selector, chainedFactory, page, selectorCache, fingerprintedSelectors, pendingReports);
      return subLoc;
    };
  }

  const origNth = loc.nth?.bind(loc);
  if (typeof origNth === 'function') {
    loc.nth = (index: number) => {
      const subLoc = origNth(index);
      const chainedFactory = (sel: string) => originalLocator(sel).nth(index);
      wrapLocatorActions(subLoc, selector, chainedFactory, page, selectorCache, fingerprintedSelectors, pendingReports);
      return subLoc;
    };
  }

  const origFilter = loc.filter?.bind(loc);
  if (typeof origFilter === 'function') {
    loc.filter = (options: any) => {
      const subLoc = origFilter(options);
      const chainedFactory = (sel: string) => originalLocator(sel).filter(options);
      wrapLocatorActions(subLoc, selector, chainedFactory, page, selectorCache, fingerprintedSelectors, pendingReports);
      return subLoc;
    };
  }
}

function wrapPageWithHealing(
  page: Page,
  fingerprintedSelectors: Set<string>,
  pendingReports: Array<Promise<void>>,
): void {
  if ((page as any).__qabotHealingWrapped) return;
  (page as any).__qabotHealingWrapped = true;

  const originalLocator = page.locator.bind(page);
  const selectorCache = new Map<string, string>();

  (page as any).locator = (selector: string, options?: any) => {
    const resolved = selectorCache.get(selector) || selector;
    const loc = originalLocator(resolved, options);
    wrapLocatorActions(loc, selector, originalLocator, page, selectorCache, fingerprintedSelectors, pendingReports);
    return loc;
  };

  // ── Wrap getBy* methods for healing + fingerprinting ──
  // These return Locator objects like page.locator(), but use Playwright's
  // built-in semantic selectors (text, role, label, etc.). Wrapping them
  // enables strict-mode auto-disambiguation, action healing, and fingerprinting.
  // captureFingerprint (querySelector) returns null for these selectors, but
  // captureFingerprintFromLocator (locator.evaluate) extracts the fingerprint.
  const GETBY_METHODS = ['getByText', 'getByRole', 'getByTestId', 'getByLabel', 'getByPlaceholder', 'getByAltText', 'getByTitle'];
  for (const method of GETBY_METHODS) {
    const origMethod = (page as any)[method]?.bind(page);
    if (typeof origMethod !== 'function') continue;
    (page as any)[method] = (...args: any[]) => {
      const loc = origMethod(...args);
      const selectorDesc = \`\${method}:\${typeof args[0] === 'string' ? args[0] : JSON.stringify(args[0])}\`;
      wrapLocatorActions(loc, selectorDesc, originalLocator, page, selectorCache, fingerprintedSelectors, pendingReports);
      return loc;
    };
  }
}

/**
 * Custom Playwright fixture that overrides the built-in \`page\` with healing.
 * Tests use \`page\` as normal — no \`healingPage\` needed.
 */
export const test = base.extend({
  page: async ({ page }, use) => {
    const fingerprintedSelectors = new Set<string>();
    const pendingReports: Array<Promise<void>> = [];

    // One-time: check healing server connectivity
    if (!healingStatusLogged) {
      healingStatusLogged = true;
      try {
        const resp = await fetch(\`\${HEALING_SERVER}/api/heal/events\`, { signal: AbortSignal.timeout(2000) });
        if (resp.ok) {
          console.log(\`[qabot-heal] Connected to healing server at \${HEALING_SERVER}\`);
        } else {
          console.log(\`[qabot-heal] Healing server responded with status \${resp.status}\`);
        }
      } catch {
        console.log(\`[qabot-heal] Healing server not running at \${HEALING_SERVER} -- auto-healing disabled\`);
      }
    }

    wrapPageWithHealing(page, fingerprintedSelectors, pendingReports);

    // Auto-wrap new pages (tabs) opened during the test — e.g. when clicking
    // a product link opens a new tab, that new Page object also gets healing.
    page.context().on('page', (newPage: Page) => {
      wrapPageWithHealing(newPage, fingerprintedSelectors, pendingReports);
    });

    await use(page);

    // After test: flush pending reports
    if (pendingReports.length > 0) {
      await Promise.allSettled(pendingReports);
    }

    // Log healing summary
    if (healingLog.length > 0) {
      console.log(\`\\n[qabot-heal] Test healed \${healingLog.length} selector(s):\`);
      for (const entry of healingLog) {
        console.log(\`  \\x1b[31m\${entry.selector}\\x1b[0m -> \\x1b[32m\${entry.healed}\\x1b[0m (\${Math.round(entry.confidence * 100)}%)\`);
      }
      healingLog.length = 0;
    }
    fingerprintedSelectors.clear();
  },
});

export { expect } from '@playwright/test';
`;

    return files;
  },

  getIntegrationInstructions(config: HealingAdapterConfig): string {
    return `
## Playwright Self-Healing Integration

### Generated Files:
- tests/helpers/healing-client.ts — HTTP client for qabot healing API
- tests/fixtures/healing.ts — Custom fixture that wraps \`page\` with self-healing

### Usage:
1. Start qabot UI server (port 3700): \`qabot /buildUI\` or \`qabot\` then \`/ui\`
2. In your test files, change only the import line:

   \`\`\`typescript
   // Before:
   import { test, expect } from '@playwright/test';

   // After:
   import { test, expect } from './fixtures/healing';
   \`\`\`

3. Run tests as normal — \`page\` is automatically wrapped with healing, no other changes needed

### How It Works:
- Overrides the built-in \`page\` fixture — tests use \`page\` as normal
- On success: captures element fingerprints and stores via qabot API
- On failure: requests healed selectors from qabot's 3-phase healing engine
- Auto-disambiguates strict mode violations with .first()
- Propagates healing through .first()/.nth()/.last()/.filter() chains
- Logs healed selectors with color-coded output
- All healing events tracked in qabot's dashboard at ${config.healingServerUrl}/healing
- After each test: flushes pending reports and logs healing summary
`.trim();
  },
};
