import type { HealingAdapter, HealingAdapterConfig } from './base.js';

/**
 * Robot Framework healing adapter.
 *
 * Generates:
 * 1. libraries/HealingLibrary.py — Robot Framework keyword library with self-healing
 * 2. resources/healing_config.py — Configuration for the healing client
 */
export const robotFrameworkAdapter: HealingAdapter = {
  framework: 'robotframework',
  language: 'python',
  displayName: 'Robot Framework (Python)',

  generate(config: HealingAdapterConfig): Record<string, string> {
    const files: Record<string, string> = {};

    // ── Healing Config ─────────────────────────────────────────────────────
    files['libraries/healing_config.py'] = `"""
qabot Healing Configuration for Robot Framework.
Auto-generated by qabot. Do not edit manually.
"""

HEALING_SERVER = "${config.healingServerUrl}"
CONFIDENCE_THRESHOLD = ${config.confidenceThreshold}
AI_ENABLED = ${config.enableAIFallback ? 'True' : 'False'}
FRAMEWORK = "robotframework"
LANGUAGE = "python"
`;

    // ── Healing Library ────────────────────────────────────────────────────
    files['libraries/HealingLibrary.py'] = `"""
qabot Self-Healing Library for Robot Framework.
Auto-generated by qabot. Do not edit manually.

This library provides self-healing keywords that wrap standard
SeleniumLibrary/Browser keywords. When an element is not found,
it queries the qabot healing API for alternative selectors.

Usage in .robot files:
    *** Settings ***
    Library    libraries/HealingLibrary.py

    *** Test Cases ***
    Example
        Healing Click    id=login-button
        Healing Input Text    css=.search-input    Hello World
"""

import base64
import json
import time
import urllib.request
import urllib.error
from robot.api import logger
from robot.api.deco import keyword
from robot.libraries.BuiltIn import BuiltIn

try:
    from .healing_config import HEALING_SERVER, CONFIDENCE_THRESHOLD, FRAMEWORK, LANGUAGE
except ImportError:
    HEALING_SERVER = "${config.healingServerUrl}"
    CONFIDENCE_THRESHOLD = ${config.confidenceThreshold}
    FRAMEWORK = "robotframework"
    LANGUAGE = "python"


class HealingLibrary:
    """Robot Framework keyword library with self-healing element location."""

    ROBOT_LIBRARY_SCOPE = "SUITE"

    def __init__(self, server_url=None, confidence_threshold=None):
        self.server_url = server_url or HEALING_SERVER
        self.confidence = confidence_threshold or CONFIDENCE_THRESHOLD
        self._healed_count = 0

    def _get_selenium(self):
        """Get the SeleniumLibrary or Browser instance."""
        builtin = BuiltIn()
        try:
            return builtin.get_library_instance("SeleniumLibrary")
        except RuntimeError:
            try:
                return builtin.get_library_instance("Browser")
            except RuntimeError:
                return None

    def _api_request(self, path, data=None):
        """Make an HTTP request to the qabot healing API."""
        url = f"{self.server_url}{path}"
        try:
            req = urllib.request.Request(
                url,
                data=json.dumps(data).encode("utf-8") if data else None,
                headers={"Content-Type": "application/json"},
                method="POST" if data else "GET",
            )
            with urllib.request.urlopen(req, timeout=10) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except (urllib.error.URLError, json.JSONDecodeError, OSError):
            return None

    def _store_fingerprint(self, selector, url, fingerprint):
        """Store element fingerprint for baseline."""
        self._api_request("/api/heal/fingerprint", {
            "selectorKey": f"css:{selector}",
            "url": url,
            "fingerprint": fingerprint,
            "framework": FRAMEWORK,
        })

    def _resolve_selector(self, selector, url, error_message=None):
        """Request a healed selector from qabot API."""
        data = {
            "selector": selector,
            "selectorStrategy": "css",
            "pageUrl": url,
            "framework": FRAMEWORK,
            "language": LANGUAGE,
        }
        if error_message:
            data["errorMessage"] = error_message
        result = self._api_request("/api/heal/resolve", data)
        if result and result.get("healed") and result.get("confidence", 0) >= self.confidence:
            return result
        return None

    def _report_healing(self, selector, url, healed, healed_selector=None, confidence=0, strategy=None, duration_ms=0):
        """Report healing outcome."""
        self._api_request("/api/heal/report", {
            "selectorKey": f"css:{selector}",
            "url": url,
            "healed": healed,
            "healedSelector": healed_selector,
            "confidence": confidence,
            "strategy": strategy,
            "framework": FRAMEWORK,
            "language": LANGUAGE,
            "originalSelector": selector,
            "durationMs": duration_ms,
        })

    def _get_current_url(self):
        """Get current page URL."""
        selenium = self._get_selenium()
        if selenium:
            try:
                return selenium.get_location()
            except Exception:
                pass
        return "unknown"

    def _capture_fingerprint(self, selenium, locator):
        """Capture element fingerprint via JavaScript."""
        try:
            driver = selenium.driver
            element = driver.find_element("css selector", locator)
            return driver.execute_script("""
                var el = arguments[0];
                var rect = el.getBoundingClientRect();
                return {
                    tagName: el.tagName.toLowerCase(),
                    id: el.id || null,
                    testId: el.getAttribute('data-testid') || null,
                    className: el.className || null,
                    ariaLabel: el.getAttribute('aria-label') || null,
                    name: el.getAttribute('name') || null,
                    placeholder: el.getAttribute('placeholder') || null,
                    textContent: (el.textContent || '').trim().substring(0, 100) || null,
                    type: el.type || null,
                    boundingBox: {x: rect.x, y: rect.y, width: rect.width, height: rect.height}
                };
            """, element)
        except Exception:
            return None

    def _resolve_ai(self, selector, url, error_message=None, test_context=None):
        """Request AI-based healing (LLM fallback)."""
        try:
            body = {
                "selector": selector,
                "selectorStrategy": "css",
                "pageUrl": url,
                "framework": FRAMEWORK,
                "language": LANGUAGE,
                "errorMessage": error_message,
                "requestAI": True,
            }
            if test_context:
                body["testContext"] = test_context
            result = self._api_request("/api/heal/resolve", body)
            if result and result.get("healed") and result.get("selector"):
                return result
            return None
        except Exception:
            return None

    def _resolve_vision(self, selector, url, screenshot_base64, test_context=None):
        """Request vision-based healing (screenshot + multimodal LLM)."""
        try:
            req_url = f"{self.server_url}/api/heal/vision"
            body = {
                "selector": selector,
                "pageUrl": url,
                "screenshotBase64": screenshot_base64,
                "framework": FRAMEWORK,
                "language": LANGUAGE,
            }
            if test_context:
                body["errorMessage"] = test_context.get("errorMessage")
                body["testContext"] = test_context
            req = urllib.request.Request(
                req_url,
                data=json.dumps(body).encode("utf-8"),
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                if data.get("healed") and data.get("selector"):
                    return data
            return None
        except (urllib.error.URLError, json.JSONDecodeError, OSError):
            return None

    def _get_screenshot_base64(self, selenium):
        """Get a base64-encoded screenshot from the browser."""
        try:
            driver = selenium.driver
            return driver.get_screenshot_as_base64()
        except Exception:
            return None

    def _try_heal_with_fallback(self, selenium, locator, url, err_msg, action_fn, keyword_name=None):
        """3-phase healing strategy chain shared by all healing keywords.

        Args:
            selenium: SeleniumLibrary or Browser instance
            locator: the original locator that failed
            url: current page URL
            err_msg: error message from the original failure
            action_fn: callable(healed_selector) that retries the action
            keyword_name: name of the healing keyword that triggered this (e.g. "Healing Click")

        Returns:
            The result of action_fn if healing succeeds, or None

        Raises:
            Nothing — caller should raise original_error if this returns None
        """
        start = time.time()

        # Build test context from Robot Framework built-in variables
        test_context = {
            "errorMessage": err_msg,
            "framework": FRAMEWORK,
            "language": LANGUAGE,
        }
        try:
            test_name = BuiltIn().get_variable_value("\${TEST NAME}")
            if test_name:
                test_context["testName"] = test_name
        except Exception:
            pass
        if keyword_name:
            test_context["keywordName"] = keyword_name

        # Phase 1: Deterministic candidates (fingerprint, similarSelector, textMatch, ancestorSearch)
        heal_result = self._resolve_selector(locator, url, error_message=err_msg)
        if heal_result and heal_result.get("selector") and heal_result["selector"] != locator:
            candidates = [{"selector": heal_result["selector"], "strategy": heal_result.get("strategy", "fingerprint")}]
            for c in heal_result.get("candidates", []):
                if c.get("selector") and c["selector"] != locator and c["selector"] != heal_result["selector"]:
                    candidates.append(c)

            for i, candidate in enumerate(candidates):
                label = "Trying" if i == 0 else "Fallback"
                logger.info(f"[qabot-heal] {label}: '{locator}' -> '{candidate['selector']}' "
                          f"(strategy: {candidate['strategy']}"
                          f"{f', attempt {i+1}/{len(candidates)}' if i > 0 else ''})")
                try:
                    result = action_fn(candidate["selector"])
                    duration = int((time.time() - start) * 1000)
                    self._report_healing(locator, url, True, candidate["selector"],
                                        heal_result.get("confidence", 0), candidate["strategy"], duration)
                    self._healed_count += 1
                    return result
                except Exception:
                    pass  # try next candidate

        # Phase 2: AI text-based healing (LLM fallback)
        try:
            ai_result = self._resolve_ai(locator, url, err_msg, test_context=test_context)
            if ai_result and ai_result.get("selector") and ai_result["selector"] != locator:
                logger.info(f"[qabot-heal] AI: '{locator}' -> '{ai_result['selector']}' "
                          f"(confidence: {ai_result.get('confidence', 0)}, strategy: aiHealing)")
                try:
                    result = action_fn(ai_result["selector"])
                    duration = int((time.time() - start) * 1000)
                    self._report_healing(locator, url, True, ai_result["selector"],
                                        ai_result.get("confidence", 0), "aiHealing", duration)
                    self._healed_count += 1
                    return result
                except Exception:
                    pass  # AI suggestion didn't work
        except Exception:
            pass  # AI healing unavailable

        # Phase 3: Vision healing (screenshot + multimodal LLM)
        try:
            b64 = self._get_screenshot_base64(selenium)
            if b64:
                vision_result = self._resolve_vision(locator, url, b64, test_context=test_context)
                if vision_result and vision_result.get("selector") and vision_result["selector"] != locator:
                    logger.info(f"[qabot-heal] Vision: '{locator}' -> '{vision_result['selector']}' "
                              f"(confidence: {vision_result.get('confidence', 0)}, strategy: visionHealing)")
                    try:
                        result = action_fn(vision_result["selector"])
                        duration = int((time.time() - start) * 1000)
                        self._report_healing(locator, url, True, vision_result["selector"],
                                            vision_result.get("confidence", 0), "visionHealing", duration)
                        self._healed_count += 1
                        return result
                    except Exception:
                        pass  # Vision suggestion didn't work
        except Exception:
            pass  # Screenshot or vision healing unavailable

        # All strategies exhausted
        duration = int((time.time() - start) * 1000)
        self._report_healing(locator, url, False, duration_ms=duration)
        return None

    @keyword("Healing Click")
    def healing_click(self, locator):
        """Click element with self-healing. Falls back to qabot API on failure."""
        selenium = self._get_selenium()
        if not selenium:
            raise RuntimeError("Neither SeleniumLibrary nor Browser library found")

        url = self._get_current_url()

        try:
            selenium.click_element(locator)
            # Success — store fingerprint
            fp = self._capture_fingerprint(selenium, locator)
            if fp:
                self._store_fingerprint(locator, url, fp)
        except Exception as original_error:
            err_msg = str(original_error)
            result = self._try_heal_with_fallback(
                selenium, locator, url, err_msg,
                lambda sel: selenium.click_element(sel),
                keyword_name="Healing Click"
            )
            if result is not None:
                return
            raise original_error

    @keyword("Healing Input Text")
    def healing_input_text(self, locator, text):
        """Input text with self-healing."""
        selenium = self._get_selenium()
        if not selenium:
            raise RuntimeError("Neither SeleniumLibrary nor Browser library found")

        url = self._get_current_url()

        try:
            selenium.input_text(locator, text)
            fp = self._capture_fingerprint(selenium, locator)
            if fp:
                self._store_fingerprint(locator, url, fp)
        except Exception as original_error:
            err_msg = str(original_error)
            result = self._try_heal_with_fallback(
                selenium, locator, url, err_msg,
                lambda sel: selenium.input_text(sel, text),
                keyword_name="Healing Input Text"
            )
            if result is not None:
                return
            raise original_error

    @keyword("Healing Get Text")
    def healing_get_text(self, locator):
        """Get element text with self-healing."""
        selenium = self._get_selenium()
        if not selenium:
            raise RuntimeError("Neither SeleniumLibrary nor Browser library found")

        url = self._get_current_url()

        try:
            text = selenium.get_text(locator)
            fp = self._capture_fingerprint(selenium, locator)
            if fp:
                self._store_fingerprint(locator, url, fp)
            return text
        except Exception as original_error:
            err_msg = str(original_error)
            result = self._try_heal_with_fallback(
                selenium, locator, url, err_msg,
                lambda sel: selenium.get_text(sel),
                keyword_name="Healing Get Text"
            )
            if result is not None:
                return result
            raise original_error

    @keyword("Healing Wait Until Element Is Visible")
    def healing_wait_until_visible(self, locator, timeout=None):
        """Wait for element with self-healing."""
        selenium = self._get_selenium()
        if not selenium:
            raise RuntimeError("Neither SeleniumLibrary nor Browser library found")

        url = self._get_current_url()

        try:
            selenium.wait_until_element_is_visible(locator, timeout)
            fp = self._capture_fingerprint(selenium, locator)
            if fp:
                self._store_fingerprint(locator, url, fp)
        except Exception as original_error:
            err_msg = str(original_error)
            result = self._try_heal_with_fallback(
                selenium, locator, url, err_msg,
                lambda sel: selenium.wait_until_element_is_visible(sel, timeout),
                keyword_name="Healing Wait Until Element Is Visible"
            )
            if result is not None:
                return
            raise original_error

    @keyword("Healing Summary")
    def healing_summary(self):
        """Log a summary of healing events in this suite."""
        if self._healed_count > 0:
            logger.info(f"[qabot-heal] Self-healed {self._healed_count} selector(s) in this suite")
        return self._healed_count
`;

    return files;
  },

  getIntegrationInstructions(config: HealingAdapterConfig): string {
    return `
## Robot Framework Self-Healing Integration

### Generated Files:
- libraries/HealingLibrary.py — Robot Framework keyword library with self-healing
- libraries/healing_config.py — Healing configuration

### Setup:
1. Start qabot UI server: \`qabot /buildUI\`
2. Add the library to your .robot file:

   \`\`\`robotframework
   *** Settings ***
   Library    SeleniumLibrary
   Library    libraries/HealingLibrary.py
   \`\`\`

### Healing Keywords:
- \`Healing Click    locator\` — Click with self-healing
- \`Healing Input Text    locator    text\` — Type text with self-healing
- \`Healing Get Text    locator\` — Get text with self-healing
- \`Healing Wait Until Element Is Visible    locator\` — Wait with self-healing
- \`Healing Summary\` — Log healing stats for the suite

### How It Works:
- On success: captures element fingerprints and stores them via qabot API
- On failure: requests healed selectors from qabot's healing engine
- Logs: [qabot-heal] Healed: "old" → "new"
- Dashboard: ${config.healingServerUrl}/healing
`.trim();
  },
};
