import type { HealingAdapter, HealingAdapterConfig } from './base.js';

/**
 * Selenium C# / NUnit healing adapter.
 *
 * Generates:
 * 1. Healing/HealingConfig.cs — Static configuration
 * 2. Healing/HealingClient.cs — HttpClient wrapper
 * 3. Healing/ElementFingerprinter.cs — JS-based fingerprinting
 * 4. Healing/HealingWebDriver.cs — IWebDriver proxy with self-healing
 * 5. Healing/HealingSetup.cs — NUnit SetUpFixture
 */
export const seleniumCSharpAdapter: HealingAdapter = {
  framework: 'selenium',
  language: 'csharp',
  displayName: 'Selenium WebDriver (C#)',

  generate(config: HealingAdapterConfig): Record<string, string> {
    const files: Record<string, string> = {};

    // ── HealingConfig.cs ──────────────────────────────────────────────
    files['Healing/HealingConfig.cs'] = `// qabot Self-Healing Configuration. Auto-generated by qabot.
namespace Healing
{
    public static class HealingConfig
    {
        public const string HealingServerUrl = "${config.healingServerUrl}";
        public const double ConfidenceThreshold = ${config.confidenceThreshold};
        public const bool AiEnabled = ${config.enableAIFallback ? 'true' : 'false'};
        public const bool Enabled = true;
        public const string Framework = "selenium";
        public const string Language = "csharp";
    }
}
`;

    // ── HealingClient.cs ──────────────────────────────────────────────
    files['Healing/HealingClient.cs'] = `// qabot Self-Healing HTTP Client. Auto-generated by qabot.
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace Healing
{
    public class HealCandidate
    {
        public string? Selector { get; set; }
        public string? Strategy { get; set; }
    }

    public class HealResult
    {
        public bool Healed { get; set; }
        public string? Selector { get; set; }
        public string? SelectorStrategy { get; set; }
        public double Confidence { get; set; }
        public string? Strategy { get; set; }
        public int DurationMs { get; set; }
        public List<HealCandidate>? Candidates { get; set; }
    }

    public class HealingClient : IDisposable
    {
        private readonly HttpClient _http;
        private readonly string _serverUrl;

        public HealingClient(string? serverUrl = null)
        {
            _serverUrl = serverUrl ?? HealingConfig.HealingServerUrl;
            _http = new HttpClient { Timeout = TimeSpan.FromSeconds(5) };
        }

        public async Task<HealResult?> ResolveAsync(string selector, string pageUrl, string? errorMessage = null)
        {
            try
            {
                var body = JsonSerializer.Serialize(new
                {
                    selector,
                    selectorStrategy = "css",
                    pageUrl,
                    framework = HealingConfig.Framework,
                    language = HealingConfig.Language,
                    errorMessage
                });
                var content = new StringContent(body, Encoding.UTF8, "application/json");
                var response = await _http.PostAsync($"{_serverUrl}/api/heal/resolve", content);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    return JsonSerializer.Deserialize<HealResult>(json, new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    });
                }
            }
            catch { /* server not running */ }
            return null;
        }

        public async Task<HealResult?> ResolveAIAsync(string selector, string pageUrl, string? errorMessage = null, Dictionary<string, string>? testContext = null)
        {
            try
            {
                var requestBody = new Dictionary<string, object?>
                {
                    ["selector"] = selector,
                    ["selectorStrategy"] = "css",
                    ["pageUrl"] = pageUrl,
                    ["framework"] = HealingConfig.Framework,
                    ["language"] = HealingConfig.Language,
                    ["errorMessage"] = errorMessage,
                    ["requestAI"] = true
                };
                if (testContext != null && testContext.Count > 0)
                {
                    requestBody["testContext"] = testContext;
                }
                var body = JsonSerializer.Serialize(requestBody);
                var content = new StringContent(body, Encoding.UTF8, "application/json");
                var response = await _http.PostAsync($"{_serverUrl}/api/heal/resolve", content);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<HealResult>(json, new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    });
                    if (result != null && result.Healed && !string.IsNullOrEmpty(result.Selector))
                        return result;
                }
            }
            catch { /* AI healing unavailable */ }
            return null;
        }

        public async Task<HealResult?> ResolveVisionAsync(string selector, string pageUrl, string screenshotBase64, Dictionary<string, string>? testContext = null)
        {
            try
            {
                var requestBody = new Dictionary<string, object?>
                {
                    ["selector"] = selector,
                    ["pageUrl"] = pageUrl,
                    ["screenshotBase64"] = screenshotBase64,
                    ["framework"] = HealingConfig.Framework,
                    ["language"] = HealingConfig.Language
                };
                if (testContext != null)
                {
                    if (testContext.ContainsKey("errorMessage"))
                        requestBody["errorMessage"] = testContext["errorMessage"];
                    if (testContext.Count > 0)
                        requestBody["testContext"] = testContext;
                }
                var body = JsonSerializer.Serialize(requestBody);
                var content = new StringContent(body, Encoding.UTF8, "application/json");
                var response = await _http.PostAsync($"{_serverUrl}/api/heal/vision", content);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    var result = JsonSerializer.Deserialize<HealResult>(json, new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    });
                    if (result != null && result.Healed && !string.IsNullOrEmpty(result.Selector))
                        return result;
                }
            }
            catch { /* Vision healing unavailable */ }
            return null;
        }

        public async Task StoreFingerprintAsync(string selectorKey, string url, object fingerprint)
        {
            try
            {
                var body = JsonSerializer.Serialize(new
                {
                    selectorKey, url, fingerprint,
                    framework = HealingConfig.Framework
                });
                var content = new StringContent(body, Encoding.UTF8, "application/json");
                await _http.PostAsync($"{_serverUrl}/api/heal/fingerprint", content);
            }
            catch { /* ignore */ }
        }

        public async Task ReportAsync(string selectorKey, string url, bool healed,
            string? healedSelector = null, double confidence = 0, string? strategy = null)
        {
            try
            {
                var body = JsonSerializer.Serialize(new
                {
                    selectorKey, url, healed, healedSelector, confidence, strategy,
                    framework = HealingConfig.Framework,
                    language = HealingConfig.Language,
                    originalSelector = selectorKey
                });
                var content = new StringContent(body, Encoding.UTF8, "application/json");
                await _http.PostAsync($"{_serverUrl}/api/heal/report", content);
            }
            catch { /* ignore */ }
        }

        public void Dispose() => _http.Dispose();
    }
}
`;

    // ── ElementFingerprinter.cs ───────────────────────────────────────
    files['Healing/ElementFingerprinter.cs'] = `// qabot Element Fingerprinter. Auto-generated by qabot.
using System.Collections.Generic;
using OpenQA.Selenium;

namespace Healing
{
    public static class ElementFingerprinter
    {
        public static Dictionary<string, object?> Capture(IWebDriver driver, IWebElement element)
        {
            try
            {
                var js = (IJavaScriptExecutor)driver;
                var result = js.ExecuteScript(@"
                    var el = arguments[0];
                    var rect = el.getBoundingClientRect();
                    return {
                        tagName: el.tagName.toLowerCase(),
                        id: el.id || null,
                        testId: el.getAttribute('data-testid') || null,
                        className: el.className || null,
                        ariaLabel: el.getAttribute('aria-label') || null,
                        ariaRole: el.getAttribute('role') || null,
                        name: el.getAttribute('name') || null,
                        placeholder: el.getAttribute('placeholder') || null,
                        textContent: (el.textContent || '').trim().substring(0, 100) || null,
                        href: el.href || null,
                        type: el.type || null,
                        boundingBox: { x: rect.x, y: rect.y, width: rect.width, height: rect.height },
                        parentTag: el.parentElement ? el.parentElement.tagName.toLowerCase() : null,
                        siblingIndex: el.parentElement ? Array.from(el.parentElement.children).indexOf(el) : -1,
                        childCount: el.children.length
                    };
                ", element);

                if (result is Dictionary<string, object?> dict) return dict;
            }
            catch { /* fingerprinting failed */ }
            return new Dictionary<string, object?>();
        }
    }
}
`;

    // ── HealingWebDriver.cs ──────────────────────────────────────────
    files['Healing/HealingWebDriver.cs'] = `// qabot Self-Healing WebDriver Proxy. Auto-generated by qabot.
//
// Usage:
//   var rawDriver = new ChromeDriver();
//   var driver = new HealingWebDriver(rawDriver);
//   driver.FindElement(By.CssSelector("#submit")); // auto-heals on failure
//
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading.Tasks;
using OpenQA.Selenium;

namespace Healing
{
    public class HealingWebDriver : IWebDriver, IJavaScriptExecutor, ITakesScreenshot
    {
        private readonly IWebDriver _delegate;
        private readonly HealingClient _client;

        public HealingWebDriver(IWebDriver driver)
        {
            _delegate = driver;
            _client = new HealingClient();
        }

        public IWebElement FindElement(By by)
        {
            if (!HealingConfig.Enabled) return _delegate.FindElement(by);

            try
            {
                var element = _delegate.FindElement(by);
                StoreBaselineAsync(by, element).ConfigureAwait(false);
                return element;
            }
            catch (NoSuchElementException ex)
            {
                return TryHealAsync(by, ex).GetAwaiter().GetResult();
            }
        }

        public ReadOnlyCollection<IWebElement> FindElements(By by)
        {
            return _delegate.FindElements(by);
        }

        private async Task<IWebElement> TryHealAsync(By by, NoSuchElementException originalError)
        {
            var selector = ExtractSelector(by);
            var selectorKey = $"css:{selector}";
            var pageUrl = _delegate.Url;
            var errorMsg = originalError.Message;

            // ── Phase 1: Deterministic candidates (fingerprint, similarSelector, textMatch, ancestorSearch) ──
            var result = await _client.ResolveAsync(selector, pageUrl, errorMsg);
            if (result != null && result.Healed && !string.IsNullOrEmpty(result.Selector) && result.Selector != selector)
            {
                // Build ordered candidate list: best match first, then remaining candidates
                var candidates = new List<(string Selector, string Strategy)>
                {
                    (result.Selector, result.Strategy ?? "fingerprint")
                };
                if (result.Candidates != null)
                {
                    foreach (var c in result.Candidates)
                    {
                        if (!string.IsNullOrEmpty(c.Selector) && c.Selector != selector && c.Selector != result.Selector)
                            candidates.Add((c.Selector!, c.Strategy ?? "unknown"));
                    }
                }

                for (int i = 0; i < candidates.Count; i++)
                {
                    var candidate = candidates[i];
                    Console.WriteLine(
                        $"[qabot-heal] {(i == 0 ? "Trying" : "Fallback")}: \\"{selector}\\" -> \\"{candidate.Selector}\\" " +
                        $"(strategy: {candidate.Strategy}{(i > 0 ? $", attempt {i + 1}/{candidates.Count}" : "")})");
                    try
                    {
                        var healed = _delegate.FindElement(By.CssSelector(candidate.Selector));
                        await _client.ReportAsync(selectorKey, pageUrl, true,
                            candidate.Selector, result.Confidence, candidate.Strategy);
                        await StoreBaselineAsync(By.CssSelector(candidate.Selector), healed);
                        return healed;
                    }
                    catch (NoSuchElementException)
                    {
                        // This candidate failed — try next
                    }
                }
            }

            // ── Phase 2: AI text-based healing (LLM fallback) ──
            try
            {
                var aiResult = await _client.ResolveAIAsync(selector, pageUrl, errorMsg, null);
                if (aiResult != null && aiResult.Healed && !string.IsNullOrEmpty(aiResult.Selector) && aiResult.Selector != selector)
                {
                    Console.WriteLine(
                        $"[qabot-heal] AI: \\"{selector}\\" -> \\"{aiResult.Selector}\\" " +
                        $"(confidence: {Math.Round(aiResult.Confidence * 100)}%, strategy: aiHealing)");
                    try
                    {
                        var healed = _delegate.FindElement(By.CssSelector(aiResult.Selector));
                        await _client.ReportAsync(selectorKey, pageUrl, true,
                            aiResult.Selector, aiResult.Confidence, "aiHealing");
                        await StoreBaselineAsync(By.CssSelector(aiResult.Selector), healed);
                        return healed;
                    }
                    catch (NoSuchElementException)
                    {
                        // AI suggestion didn't work — try vision
                    }
                }
            }
            catch { /* AI healing unavailable */ }

            // ── Phase 3: Vision healing (screenshot + multimodal LLM) ──
            try
            {
                var screenshotBase64 = ((ITakesScreenshot)_delegate).GetScreenshot().AsBase64EncodedString;
                var visionResult = await _client.ResolveVisionAsync(selector, pageUrl, screenshotBase64, null);
                if (visionResult != null && visionResult.Healed && !string.IsNullOrEmpty(visionResult.Selector) && visionResult.Selector != selector)
                {
                    Console.WriteLine(
                        $"[qabot-heal] Vision: \\"{selector}\\" -> \\"{visionResult.Selector}\\" " +
                        $"(confidence: {Math.Round(visionResult.Confidence * 100)}%, strategy: visionHealing)");
                    try
                    {
                        var healed = _delegate.FindElement(By.CssSelector(visionResult.Selector));
                        await _client.ReportAsync(selectorKey, pageUrl, true,
                            visionResult.Selector, visionResult.Confidence, "visionHealing");
                        await StoreBaselineAsync(By.CssSelector(visionResult.Selector), healed);
                        return healed;
                    }
                    catch (NoSuchElementException)
                    {
                        // Vision suggestion didn't work either
                    }
                }
            }
            catch { /* Screenshot or vision healing unavailable */ }

            // All strategies exhausted — report failure and throw original error
            await _client.ReportAsync(selectorKey, pageUrl, false);
            throw originalError;
        }

        private async Task StoreBaselineAsync(By by, IWebElement element)
        {
            try
            {
                var selector = ExtractSelector(by);
                var selectorKey = $"css:{selector}";
                var fp = ElementFingerprinter.Capture(_delegate, element);
                if (fp.Count > 0)
                {
                    await _client.StoreFingerprintAsync(selectorKey, _delegate.Url, fp);
                }
            }
            catch { /* ignore */ }
        }

        private static string ExtractSelector(By by)
        {
            var desc = by.ToString();
            // By.CssSelector: css selector -> value
            if (desc.Contains("By.CssSelector:")) return desc.Split(':')[1]?.Trim() ?? desc;
            if (desc.Contains("By.Id:")) return "#" + desc.Split(':')[1]?.Trim();
            if (desc.Contains("By.Name:")) return $"[name=\\"{desc.Split(':')[1]?.Trim()}\\"]";
            if (desc.Contains("By.ClassName:")) return "." + desc.Split(':')[1]?.Trim();
            if (desc.Contains("By.TagName:")) return desc.Split(':')[1]?.Trim() ?? desc;
            return desc;
        }

        // ── Delegate IWebDriver members ──────────────────────────────

        public string Url { get => _delegate.Url; set => _delegate.Url = value; }
        public string Title => _delegate.Title;
        public string PageSource => _delegate.PageSource;
        public string CurrentWindowHandle => _delegate.CurrentWindowHandle;
        public ReadOnlyCollection<string> WindowHandles => _delegate.WindowHandles;

        public void Close() => _delegate.Close();
        public void Quit() { _delegate.Quit(); _client.Dispose(); }
        public IOptions Manage() => _delegate.Manage();
        public INavigation Navigate() => _delegate.Navigate();
        public ITargetLocator SwitchTo() => _delegate.SwitchTo();
        public void Dispose() { _delegate.Dispose(); _client.Dispose(); }

        // ── IJavaScriptExecutor ──────────────────────────────────────

        public object ExecuteScript(string script, params object[] args)
            => ((IJavaScriptExecutor)_delegate).ExecuteScript(script, args);

        public object ExecuteAsyncScript(string script, params object[] args)
            => ((IJavaScriptExecutor)_delegate).ExecuteAsyncScript(script, args);

        // ── ITakesScreenshot ─────────────────────────────────────────

        public Screenshot GetScreenshot()
            => ((ITakesScreenshot)_delegate).GetScreenshot();
    }
}
`;

    // ── HealingSetup.cs ──────────────────────────────────────────────
    files['Healing/HealingSetup.cs'] = `// qabot Self-Healing NUnit Setup. Auto-generated by qabot.
using NUnit.Framework;

namespace Healing
{
    [SetUpFixture]
    public class HealingSetup
    {
        [OneTimeSetUp]
        public void GlobalSetup()
        {
            if (HealingConfig.Enabled)
            {
                TestContext.Progress.WriteLine(
                    $"[qabot-heal] Self-healing enabled. Server: {HealingConfig.HealingServerUrl}");
            }
        }

        [OneTimeTearDown]
        public void GlobalTeardown()
        {
            if (HealingConfig.Enabled)
            {
                TestContext.Progress.WriteLine(
                    $"[qabot-heal] Dashboard: {HealingConfig.HealingServerUrl}/healing");
            }
        }
    }
}
`;

    return files;
  },

  getIntegrationInstructions(config: HealingAdapterConfig): string {
    return `
## Selenium C# Self-Healing Integration

### Generated Files:
- Healing/HealingConfig.cs — Configuration
- Healing/HealingClient.cs — HTTP client
- Healing/ElementFingerprinter.cs — Element attribute capture
- Healing/HealingWebDriver.cs — Self-healing IWebDriver proxy
- Healing/HealingSetup.cs — NUnit global setup

### Setup:
1. Start qabot UI server: \`qabot /buildUI\` or \`qabot\` then \`/ui\`
2. Add the generated Healing/ folder to your test project
3. Wrap your WebDriver:

   \`\`\`csharp
   // Before:
   IWebDriver driver = new ChromeDriver();

   // After:
   using Healing;
   IWebDriver driver = new HealingWebDriver(new ChromeDriver());
   \`\`\`

4. All FindElement() calls will now auto-heal on failure
5. View healing stats at ${config.healingServerUrl}/healing

### How It Works:
- On FindElement() success: captures element fingerprint via JavaScript
- On NoSuchElementException: requests healed selector from qabot API, retries
- Logs: [qabot-heal] Healed: "#old" -> "[data-testid=\\"new\\"]"
`.trim();
  },
};
