import type { HealingAdapter, HealingAdapterConfig } from './base.js';

/**
 * Selenium Java healing adapter.
 *
 * Generates:
 * 1. src/test/java/healing/HealingClient.java — HTTP client for qabot API
 * 2. src/test/java/healing/ElementFingerprinter.java — Captures element attributes
 * 3. src/test/java/healing/HealingWebDriver.java — Proxy WebDriver with self-healing
 * 4. src/test/java/healing/HealingConfig.java — Configuration
 * 5. src/test/java/healing/HealingExtension.java — JUnit5 extension for auto-setup
 */
export const seleniumJavaAdapter: HealingAdapter = {
  framework: 'selenium',
  language: 'java',
  displayName: 'Selenium WebDriver (Java)',

  generate(config: HealingAdapterConfig): Record<string, string> {
    const files: Record<string, string> = {};

    // ── HealingConfig.java ─────────────────────────────────────────────────
    files['src/test/java/healing/HealingConfig.java'] = `package healing;

/**
 * qabot Self-Healing Configuration.
 * Auto-generated by qabot. Modify as needed.
 */
public class HealingConfig {
    public static final String HEALING_SERVER_URL = "${config.healingServerUrl}";
    public static final double CONFIDENCE_THRESHOLD = ${config.confidenceThreshold};
    public static final boolean AI_ENABLED = ${config.enableAIFallback};
    public static final boolean ENABLED = true;
    public static final String FRAMEWORK = "selenium";
    public static final String LANGUAGE = "java";
}
`;

    // ── HealingClient.java ─────────────────────────────────────────────────
    files['src/test/java/healing/HealingClient.java'] = `package healing;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/**
 * HTTP client for qabot's self-healing API.
 * Auto-generated by qabot.
 */
public class HealingClient {
    private final HttpClient client;
    private final String serverUrl;

    public HealingClient() {
        this(HealingConfig.HEALING_SERVER_URL);
    }

    public HealingClient(String serverUrl) {
        this.serverUrl = serverUrl;
        this.client = HttpClient.newBuilder()
            .connectTimeout(java.time.Duration.ofSeconds(5))
            .build();
    }

    /**
     * Store a baseline fingerprint for a selector.
     */
    public void storeFingerprint(String selectorKey, String url, Map<String, Object> fingerprint) {
        try {
            String json = buildJson(Map.of(
                "selectorKey", selectorKey,
                "url", url,
                "fingerprint", fingerprint,
                "framework", HealingConfig.FRAMEWORK
            ));
            post("/api/heal/fingerprint", json);
        } catch (Exception e) {
            // qabot server not running — continue silently
        }
    }

    /**
     * Request a healed selector for a broken one.
     */
    public HealResult resolve(String selector, String pageUrl) {
        return resolve(selector, pageUrl, null);
    }

    public HealResult resolve(String selector, String pageUrl, String errorMessage) {
        try {
            Map<String, Object> body = new HashMap<>();
            body.put("selector", selector);
            body.put("selectorStrategy", "css");
            body.put("pageUrl", pageUrl);
            body.put("framework", HealingConfig.FRAMEWORK);
            body.put("language", HealingConfig.LANGUAGE);
            if (errorMessage != null) body.put("errorMessage", errorMessage);
            String json = buildJson(body);
            String response = post("/api/heal/resolve", json);
            if (response == null) return null;
            return HealResult.parse(response);
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * Request AI text-based healing (LLM fallback — Phase 2).
     */
    public HealResult resolveAI(String selector, String pageUrl, String errorMessage) {
        return resolveAI(selector, pageUrl, errorMessage, null);
    }

    public HealResult resolveAI(String selector, String pageUrl, String errorMessage, Map<String, String> testContext) {
        try {
            Map<String, Object> body = new HashMap<>();
            body.put("selector", selector);
            body.put("selectorStrategy", "css");
            body.put("pageUrl", pageUrl);
            body.put("framework", HealingConfig.FRAMEWORK);
            body.put("language", HealingConfig.LANGUAGE);
            if (errorMessage != null) body.put("errorMessage", errorMessage);
            body.put("requestAI", true);
            if (testContext != null && !testContext.isEmpty()) {
                body.put("testContext", new HashMap<>(testContext));
            }
            String json = buildJson(body);
            String response = post("/api/heal/resolve", json);
            if (response == null) return null;
            return HealResult.parse(response);
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * Request Vision healing via screenshot + multimodal LLM (Phase 3).
     */
    public HealResult resolveVision(String selector, String pageUrl, String screenshotBase64) {
        return resolveVision(selector, pageUrl, screenshotBase64, null);
    }

    public HealResult resolveVision(String selector, String pageUrl, String screenshotBase64, Map<String, String> testContext) {
        try {
            Map<String, Object> body = new HashMap<>();
            body.put("selector", selector);
            body.put("pageUrl", pageUrl);
            body.put("screenshotBase64", screenshotBase64);
            body.put("framework", HealingConfig.FRAMEWORK);
            body.put("language", HealingConfig.LANGUAGE);
            if (testContext != null) {
                if (testContext.containsKey("errorMessage")) body.put("errorMessage", testContext.get("errorMessage"));
                if (!testContext.isEmpty()) body.put("testContext", new HashMap<>(testContext));
            }
            String json = buildJson(body);
            String response = post("/api/heal/vision", json);
            if (response == null) return null;
            return HealResult.parse(response);
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * Report healing outcome.
     */
    public void report(String selectorKey, String url, boolean healed,
                        String healedSelector, double confidence, String strategy) {
        try {
            Map<String, Object> body = new HashMap<>();
            body.put("selectorKey", selectorKey);
            body.put("url", url);
            body.put("healed", healed);
            body.put("framework", HealingConfig.FRAMEWORK);
            body.put("language", HealingConfig.LANGUAGE);
            body.put("originalSelector", selectorKey);
            if (healedSelector != null) body.put("healedSelector", healedSelector);
            if (confidence > 0) body.put("confidence", confidence);
            if (strategy != null) body.put("strategy", strategy);
            post("/api/heal/report", buildJson(body));
        } catch (Exception e) {
            // Silently ignore
        }
    }

    private String post(String path, String jsonBody) throws Exception {
        HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create(serverUrl + path))
            .header("Content-Type", "application/json")
            .POST(HttpRequest.BodyPublishers.ofString(jsonBody))
            .build();
        HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
        return response.statusCode() == 200 ? response.body() : null;
    }

    @SuppressWarnings("unchecked")
    private String buildJson(Map<String, Object> map) {
        StringBuilder sb = new StringBuilder("{");
        boolean first = true;
        for (Map.Entry<String, Object> entry : map.entrySet()) {
            if (!first) sb.append(",");
            first = false;
            sb.append("\\"").append(entry.getKey()).append("\\":");
            Object val = entry.getValue();
            if (val instanceof String) {
                sb.append("\\"").append(((String) val).replace("\\"", "\\\\\\"")).append("\\"");
            } else if (val instanceof Boolean) {
                sb.append(val);
            } else if (val instanceof Number) {
                sb.append(val);
            } else if (val instanceof Map) {
                sb.append(buildJson((Map<String, Object>) val));
            } else {
                sb.append("\\"").append(String.valueOf(val)).append("\\"");
            }
        }
        sb.append("}");
        return sb.toString();
    }

    /**
     * A single healing candidate (selector + strategy).
     */
    public static class HealCandidate {
        public String selector;
        public String strategy;

        public HealCandidate(String selector, String strategy) {
            this.selector = selector;
            this.strategy = strategy;
        }
    }

    /**
     * Healing result from the API.
     */
    public static class HealResult {
        public boolean healed;
        public String selector;
        public String selectorStrategy;
        public double confidence;
        public String strategy;
        public long durationMs;
        public List<HealCandidate> candidates;

        public static HealResult parse(String json) {
            HealResult result = new HealResult();
            result.healed = json.contains("\\"healed\\":true");
            result.selector = extractString(json, "selector");
            result.selectorStrategy = extractString(json, "selectorStrategy");
            result.strategy = extractString(json, "strategy");
            result.confidence = extractDouble(json, "confidence");
            result.durationMs = extractLong(json, "durationMs");
            result.candidates = parseCandidates(json);
            return result.healed ? result : null;
        }

        private static String extractString(String json, String key) {
            int idx = json.indexOf("\\"" + key + "\\":\\"");
            if (idx < 0) return null;
            int start = idx + key.length() + 4;
            int end = json.indexOf("\\"", start);
            return end > start ? json.substring(start, end) : null;
        }

        private static double extractDouble(String json, String key) {
            int idx = json.indexOf("\\"" + key + "\\":");
            if (idx < 0) return 0;
            int start = idx + key.length() + 3;
            StringBuilder sb = new StringBuilder();
            for (int i = start; i < json.length(); i++) {
                char c = json.charAt(i);
                if (Character.isDigit(c) || c == '.') sb.append(c);
                else break;
            }
            try { return Double.parseDouble(sb.toString()); } catch (Exception e) { return 0; }
        }

        private static long extractLong(String json, String key) {
            return (long) extractDouble(json, key);
        }

        /**
         * Parse the "candidates" array from JSON response.
         * Extracts [{selector, strategy}, ...] from hand-rolled JSON.
         */
        private static List<HealCandidate> parseCandidates(String json) {
            List<HealCandidate> list = new ArrayList<>();
            int idx = json.indexOf("\\"candidates\\":");
            if (idx < 0) return list;
            int arrStart = json.indexOf("[", idx);
            if (arrStart < 0) return list;
            int arrEnd = json.indexOf("]", arrStart);
            if (arrEnd < 0) return list;
            String arrStr = json.substring(arrStart + 1, arrEnd);
            // Split by "},{" to get each candidate object
            String[] parts = arrStr.split("\\\\}\\\\s*,\\\\s*\\\\{");
            for (String part : parts) {
                String clean = part.replace("{", "").replace("}", "").trim();
                if (clean.isEmpty()) continue;
                String sel = null, strat = null;
                // Extract "selector":"value"
                int sIdx = clean.indexOf("\\"selector\\":\\"");
                if (sIdx >= 0) {
                    int sStart = sIdx + 12;
                    int sEnd = clean.indexOf("\\"", sStart);
                    if (sEnd > sStart) sel = clean.substring(sStart, sEnd);
                }
                // Extract "strategy":"value"
                int stIdx = clean.indexOf("\\"strategy\\":\\"");
                if (stIdx >= 0) {
                    int stStart = stIdx + 12;
                    int stEnd = clean.indexOf("\\"", stStart);
                    if (stEnd > stStart) strat = clean.substring(stStart, stEnd);
                }
                if (sel != null) list.add(new HealCandidate(sel, strat != null ? strat : "unknown"));
            }
            return list;
        }
    }
}
`;

    // ── ElementFingerprinter.java ──────────────────────────────────────────
    files['src/test/java/healing/ElementFingerprinter.java'] = `package healing;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import java.util.Map;
import java.util.HashMap;

/**
 * Captures element attributes for fingerprinting.
 * Auto-generated by qabot.
 */
public class ElementFingerprinter {

    /**
     * Capture a fingerprint of the given element.
     */
    @SuppressWarnings("unchecked")
    public static Map<String, Object> capture(WebDriver driver, WebElement element) {
        try {
            JavascriptExecutor js = (JavascriptExecutor) driver;
            Object result = js.executeScript(
                "var el = arguments[0];" +
                "var rect = el.getBoundingClientRect();" +
                "return {" +
                "  tagName: el.tagName.toLowerCase()," +
                "  id: el.id || undefined," +
                "  testId: el.getAttribute('data-testid') || undefined," +
                "  className: el.className || undefined," +
                "  ariaLabel: el.getAttribute('aria-label') || undefined," +
                "  ariaRole: el.getAttribute('role') || undefined," +
                "  name: el.getAttribute('name') || undefined," +
                "  placeholder: el.getAttribute('placeholder') || undefined," +
                "  textContent: (el.textContent || '').trim().substring(0, 100) || undefined," +
                "  href: el.href || undefined," +
                "  type: el.type || undefined," +
                "  boundingBox: { x: rect.x, y: rect.y, width: rect.width, height: rect.height }," +
                "  parentTag: el.parentElement ? el.parentElement.tagName.toLowerCase() : undefined," +
                "  siblingIndex: el.parentElement ? Array.from(el.parentElement.children).indexOf(el) : -1," +
                "  childCount: el.children.length" +
                "};",
                element
            );
            return result instanceof Map ? (Map<String, Object>) result : new HashMap<>();
        } catch (Exception e) {
            return new HashMap<>();
        }
    }
}
`;

    // ── HealingWebDriver.java ──────────────────────────────────────────────
    files['src/test/java/healing/HealingWebDriver.java'] = `package healing;

import org.openqa.selenium.*;
import org.openqa.selenium.interactions.Sequence;
import java.util.*;

/**
 * Self-healing WebDriver proxy.
 * Intercepts findElement() and findElements() calls.
 * On failure: requests healed selector from qabot API.
 * On success: stores element fingerprint as baseline.
 *
 * Auto-generated by qabot.
 *
 * Usage:
 *   WebDriver rawDriver = new ChromeDriver();
 *   WebDriver driver = new HealingWebDriver(rawDriver);
 *   driver.findElement(By.cssSelector("#submit")); // auto-heals on failure
 */
public class HealingWebDriver implements WebDriver {
    private final WebDriver delegate;
    private final HealingClient client;

    public HealingWebDriver(WebDriver delegate) {
        this.delegate = delegate;
        this.client = new HealingClient();
    }

    @Override
    public WebElement findElement(By by) {
        if (!HealingConfig.ENABLED) {
            return delegate.findElement(by);
        }

        try {
            WebElement element = delegate.findElement(by);
            // Success — store fingerprint as baseline
            storeBaseline(by, element);
            return element;
        } catch (NoSuchElementException e) {
            // Try healing
            return tryHeal(by, e);
        }
    }

    private WebElement tryHeal(By by, NoSuchElementException originalError) {
        String selector = extractSelector(by);
        String selectorKey = "css:" + selector;
        String pageUrl = delegate.getCurrentUrl();
        String errorMsg = originalError.getMessage();

        // ── Phase 1: Deterministic candidates (fingerprint, similarSelector, textMatch, ancestorSearch) ──
        HealingClient.HealResult result = client.resolve(selector, pageUrl, errorMsg);
        if (result != null && result.selector != null && !result.selector.equals(selector)) {
            // Build ordered candidate list: best match first, then remaining candidates
            java.util.List<HealingClient.HealCandidate> candidates = new java.util.ArrayList<>();
            candidates.add(new HealingClient.HealCandidate(result.selector, result.strategy != null ? result.strategy : "fingerprint"));
            if (result.candidates != null) {
                for (HealingClient.HealCandidate c : result.candidates) {
                    if (c.selector != null && !c.selector.equals(selector) && !c.selector.equals(result.selector)) {
                        candidates.add(c);
                    }
                }
            }

            for (int i = 0; i < candidates.size(); i++) {
                HealingClient.HealCandidate candidate = candidates.get(i);
                System.out.println("[qabot-heal] " + (i == 0 ? "Trying" : "Fallback") + ": \\"" + selector + "\\" → \\"" + candidate.selector + "\\" " +
                    "(strategy: " + candidate.strategy + (i > 0 ? ", attempt " + (i + 1) + "/" + candidates.size() : "") + ")");
                try {
                    WebElement healed = delegate.findElement(By.cssSelector(candidate.selector));
                    client.report(selectorKey, pageUrl, true, candidate.selector, result.confidence, candidate.strategy);
                    storeBaseline(By.cssSelector(candidate.selector), healed);
                    return healed;
                } catch (NoSuchElementException healFail) {
                    // This candidate failed — try next
                }
            }
        }

        // ── Phase 2: AI text-based healing (LLM fallback) ──
        try {
            HealingClient.HealResult aiResult = client.resolveAI(selector, pageUrl, errorMsg, null);
            if (aiResult != null && aiResult.selector != null && !aiResult.selector.equals(selector)) {
                System.out.println("[qabot-heal] AI: \\"" + selector + "\\" → \\"" + aiResult.selector + "\\" " +
                    "(confidence: " + Math.round(aiResult.confidence * 100) + "%, strategy: aiHealing)");
                try {
                    WebElement healed = delegate.findElement(By.cssSelector(aiResult.selector));
                    client.report(selectorKey, pageUrl, true, aiResult.selector, aiResult.confidence, "aiHealing");
                    storeBaseline(By.cssSelector(aiResult.selector), healed);
                    return healed;
                } catch (NoSuchElementException healFail) {
                    // AI suggestion didn't work — try vision
                }
            }
        } catch (Exception e) {
            // AI healing unavailable
        }

        // ── Phase 3: Vision healing (screenshot + multimodal LLM) ──
        try {
            String screenshotBase64 = ((TakesScreenshot) delegate).getScreenshotAs(OutputType.BASE64);
            HealingClient.HealResult visionResult = client.resolveVision(selector, pageUrl, screenshotBase64, null);
            if (visionResult != null && visionResult.selector != null && !visionResult.selector.equals(selector)) {
                System.out.println("[qabot-heal] Vision: \\"" + selector + "\\" → \\"" + visionResult.selector + "\\" " +
                    "(confidence: " + Math.round(visionResult.confidence * 100) + "%, strategy: visionHealing)");
                try {
                    WebElement healed = delegate.findElement(By.cssSelector(visionResult.selector));
                    client.report(selectorKey, pageUrl, true, visionResult.selector, visionResult.confidence, "visionHealing");
                    storeBaseline(By.cssSelector(visionResult.selector), healed);
                    return healed;
                } catch (NoSuchElementException healFail) {
                    // Vision suggestion didn't work either
                }
            }
        } catch (Exception e) {
            // Screenshot or vision healing unavailable
        }

        // All strategies exhausted — report failure and throw original error
        client.report(selectorKey, pageUrl, false, null, 0, null);
        throw originalError;
    }

    private void storeBaseline(By by, WebElement element) {
        try {
            String selector = extractSelector(by);
            String selectorKey = "css:" + selector;
            Map<String, Object> fp = ElementFingerprinter.capture(delegate, element);
            if (!fp.isEmpty()) {
                client.storeFingerprint(selectorKey, delegate.getCurrentUrl(), fp);
            }
        } catch (Exception e) {
            // Ignore baseline storage errors
        }
    }

    private String extractSelector(By by) {
        String str = by.toString();
        // By.cssSelector: ... -> ..., By.id: ... -> #..., etc.
        if (str.startsWith("By.cssSelector: ")) return str.substring(16);
        if (str.startsWith("By.id: ")) return "#" + str.substring(7);
        if (str.startsWith("By.name: ")) return "[name=\\"" + str.substring(9) + "\\"]";
        if (str.startsWith("By.className: ")) return "." + str.substring(14);
        if (str.startsWith("By.tagName: ")) return str.substring(12);
        return str;
    }

    // ── Delegate all other WebDriver methods ─────────────────────────────

    @Override public List<WebElement> findElements(By by) { return delegate.findElements(by); }
    @Override public void get(String url) { delegate.get(url); }
    @Override public String getCurrentUrl() { return delegate.getCurrentUrl(); }
    @Override public String getTitle() { return delegate.getTitle(); }
    @Override public String getPageSource() { return delegate.getPageSource(); }
    @Override public void close() { delegate.close(); }
    @Override public void quit() { delegate.quit(); }
    @Override public Set<String> getWindowHandles() { return delegate.getWindowHandles(); }
    @Override public String getWindowHandle() { return delegate.getWindowHandle(); }
    @Override public TargetLocator switchTo() { return delegate.switchTo(); }
    @Override public Navigation navigate() { return delegate.navigate(); }
    @Override public Options manage() { return delegate.manage(); }
}
`;

    // ── HealingExtension.java ──────────────────────────────────────────────
    files['src/test/java/healing/HealingExtension.java'] = `package healing;

import org.junit.jupiter.api.extension.*;
import org.openqa.selenium.WebDriver;

/**
 * JUnit 5 Extension that automatically wraps WebDriver with HealingWebDriver.
 * Auto-generated by qabot.
 *
 * Usage:
 *   @ExtendWith(HealingExtension.class)
 *   public class MyTest {
 *       private WebDriver driver;
 *
 *       @BeforeEach
 *       void setUp() {
 *           driver = new HealingWebDriver(new ChromeDriver());
 *       }
 *   }
 *
 * Or simply wrap the driver manually without the extension:
 *   WebDriver driver = new HealingWebDriver(new ChromeDriver());
 */
public class HealingExtension implements BeforeEachCallback, AfterEachCallback {

    @Override
    public void beforeEach(ExtensionContext context) {
        System.out.println("[qabot-heal] Self-healing enabled for: " + context.getDisplayName());
    }

    @Override
    public void afterEach(ExtensionContext context) {
        if (context.getExecutionException().isPresent()) {
            System.out.println("[qabot-heal] Test failed: " + context.getDisplayName() +
                " — check healing dashboard at " + HealingConfig.HEALING_SERVER_URL + "/healing");
        }
    }
}
`;

    return files;
  },

  getIntegrationInstructions(config: HealingAdapterConfig): string {
    return `
## Selenium Java Self-Healing Integration

### Generated Files:
- src/test/java/healing/HealingConfig.java — Configuration
- src/test/java/healing/HealingClient.java — HTTP client for qabot API
- src/test/java/healing/ElementFingerprinter.java — Element attribute capture
- src/test/java/healing/HealingWebDriver.java — Self-healing WebDriver proxy
- src/test/java/healing/HealingExtension.java — JUnit 5 extension

### Usage:
1. Start qabot UI server: \`qabot /buildUI\` or \`qabot\` then \`/ui\`
2. Wrap your WebDriver with HealingWebDriver:

   \`\`\`java
   // Before:
   WebDriver driver = new ChromeDriver();

   // After:
   WebDriver driver = new HealingWebDriver(new ChromeDriver());
   \`\`\`

3. All findElement() calls will now auto-heal on failure
4. View healing stats at ${config.healingServerUrl}/healing

### How It Works:
- On findElement() success: captures element fingerprint → stores via qabot API
- On NoSuchElementException: requests healed selector from qabot → retries
- Logs: [qabot-heal] Healed: "#old" → "[data-testid=\\"new\\"]"
`.trim();
  },
};
