import type { HealingAdapter, HealingAdapterConfig } from './base.js';

/**
 * Selenium Python healing adapter.
 *
 * Generates:
 * 1. tests/healing/healing_config.py — Configuration
 * 2. tests/healing/healing_client.py — HTTP client for qabot API
 * 3. tests/healing/element_fingerprinter.py — Captures element attributes
 * 4. tests/healing/healing_webdriver.py — Proxy WebDriver with self-healing
 * 5. tests/healing/conftest_healing.py — pytest fixture for auto-setup
 * 6. tests/healing/__init__.py — Package init
 */
export const seleniumPythonAdapter: HealingAdapter = {
  framework: 'selenium',
  language: 'python',
  displayName: 'Selenium WebDriver (Python)',

  generate(config: HealingAdapterConfig): Record<string, string> {
    const files: Record<string, string> = {};

    // ── __init__.py ───────────────────────────────────────────────────────
    files['tests/healing/__init__.py'] = `"""qabot Self-Healing for Selenium Python. Auto-generated by qabot."""
from .healing_webdriver import HealingWebDriver
from .healing_client import HealingClient
from .element_fingerprinter import ElementFingerprinter
from .healing_config import HealingConfig

__all__ = ["HealingWebDriver", "HealingClient", "ElementFingerprinter", "HealingConfig"]
`;

    // ── healing_config.py ─────────────────────────────────────────────────
    files['tests/healing/healing_config.py'] = `"""qabot Self-Healing Configuration. Auto-generated by qabot."""


class HealingConfig:
    HEALING_SERVER_URL = "${config.healingServerUrl}"
    CONFIDENCE_THRESHOLD = ${config.confidenceThreshold}
    AI_ENABLED = ${config.enableAIFallback ? 'True' : 'False'}
    ENABLED = True
    FRAMEWORK = "selenium"
    LANGUAGE = "python"
`;

    // ── healing_client.py ─────────────────────────────────────────────────
    files['tests/healing/healing_client.py'] = `"""HTTP client for qabot's self-healing API. Auto-generated by qabot."""
import json
import urllib.request
import urllib.error
from typing import Optional, Dict, Any
from .healing_config import HealingConfig


class HealResult:
    """Healing result from the API."""

    def __init__(self, healed: bool = False, selector: Optional[str] = None,
                 selector_strategy: Optional[str] = None, confidence: float = 0,
                 strategy: Optional[str] = None, duration_ms: int = 0,
                 candidates: Optional[list] = None):
        self.healed = healed
        self.selector = selector
        self.selector_strategy = selector_strategy
        self.confidence = confidence
        self.strategy = strategy
        self.duration_ms = duration_ms
        self.candidates = candidates or []

    @staticmethod
    def from_json(data: dict) -> Optional["HealResult"]:
        if not data.get("healed"):
            return None
        return HealResult(
            healed=True,
            selector=data.get("selector"),
            selector_strategy=data.get("selectorStrategy"),
            confidence=data.get("confidence", 0),
            strategy=data.get("strategy"),
            duration_ms=data.get("durationMs", 0),
            candidates=data.get("candidates", []),
        )


class HealingClient:
    """HTTP client for qabot's self-healing API."""

    def __init__(self, server_url: Optional[str] = None):
        self.server_url = server_url or HealingConfig.HEALING_SERVER_URL

    def store_fingerprint(self, selector_key: str, url: str, fingerprint: Dict[str, Any]) -> None:
        """Store a baseline fingerprint for a selector."""
        try:
            self._post("/api/heal/fingerprint", {
                "selectorKey": selector_key,
                "url": url,
                "fingerprint": fingerprint,
                "framework": HealingConfig.FRAMEWORK,
            })
        except Exception:
            pass  # qabot server not running — continue silently

    def resolve(self, selector: str, page_url: str, error_message: Optional[str] = None) -> Optional[HealResult]:
        """Request a healed selector for a broken one."""
        try:
            data = {
                "selector": selector,
                "selectorStrategy": "css",
                "pageUrl": page_url,
                "framework": HealingConfig.FRAMEWORK,
                "language": HealingConfig.LANGUAGE,
            }
            if error_message:
                data["errorMessage"] = error_message
            response = self._post("/api/heal/resolve", data)
            if response is None:
                return None
            return HealResult.from_json(response)
        except Exception:
            return None

    def resolve_ai(self, selector: str, page_url: str, error_message: Optional[str] = None,
                   test_context: Optional[Dict[str, Any]] = None) -> Optional[HealResult]:
        """Request AI-based healing (LLM fallback)."""
        try:
            body: Dict[str, Any] = {
                "selector": selector,
                "selectorStrategy": "css",
                "pageUrl": page_url,
                "framework": HealingConfig.FRAMEWORK,
                "language": HealingConfig.LANGUAGE,
                "errorMessage": error_message,
                "requestAI": True,
            }
            if test_context:
                body["testContext"] = test_context
            response = self._post("/api/heal/resolve", body)
            if response and response.get("healed") and response.get("selector"):
                return HealResult.from_json(response)
            return None
        except Exception:
            return None

    def resolve_vision(self, selector: str, page_url: str, screenshot_base64: str,
                       test_context: Optional[Dict[str, Any]] = None) -> Optional[HealResult]:
        """Request vision-based healing (screenshot + multimodal LLM)."""
        try:
            url = self.server_url + "/api/heal/vision"
            body: Dict[str, Any] = {
                "selector": selector,
                "pageUrl": page_url,
                "screenshotBase64": screenshot_base64,
                "framework": HealingConfig.FRAMEWORK,
                "language": HealingConfig.LANGUAGE,
            }
            if test_context:
                body["errorMessage"] = test_context.get("errorMessage")
                body["testContext"] = test_context
            json_data = json.dumps(body).encode("utf-8")
            req = urllib.request.Request(
                url,
                data=json_data,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                if resp.status == 200:
                    data = json.loads(resp.read().decode("utf-8"))
                    if data.get("healed") and data.get("selector"):
                        return HealResult.from_json(data)
            return None
        except (urllib.error.URLError, urllib.error.HTTPError):
            return None

    def report(self, selector_key: str, url: str, healed: bool,
               healed_selector: Optional[str] = None, confidence: float = 0,
               strategy: Optional[str] = None) -> None:
        """Report healing outcome."""
        try:
            body: Dict[str, Any] = {
                "selectorKey": selector_key,
                "url": url,
                "healed": healed,
                "framework": HealingConfig.FRAMEWORK,
                "language": HealingConfig.LANGUAGE,
                "originalSelector": selector_key,
            }
            if healed_selector:
                body["healedSelector"] = healed_selector
            if confidence > 0:
                body["confidence"] = confidence
            if strategy:
                body["strategy"] = strategy
            self._post("/api/heal/report", body)
        except Exception:
            pass

    def _post(self, path: str, data: dict) -> Optional[dict]:
        """Send a POST request to the qabot healing API."""
        url = self.server_url + path
        json_data = json.dumps(data).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=json_data,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=5) as resp:
                if resp.status == 200:
                    return json.loads(resp.read().decode("utf-8"))
        except (urllib.error.URLError, urllib.error.HTTPError):
            pass
        return None
`;

    // ── element_fingerprinter.py ──────────────────────────────────────────
    files['tests/healing/element_fingerprinter.py'] = `"""Captures element attributes for fingerprinting. Auto-generated by qabot."""
from typing import Dict, Any
from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.remote.webelement import WebElement


class ElementFingerprinter:
    """Capture element attributes for baseline fingerprinting."""

    @staticmethod
    def capture(driver: WebDriver, element: WebElement) -> Dict[str, Any]:
        """Capture a fingerprint of the given element."""
        try:
            return driver.execute_script("""
                var el = arguments[0];
                var rect = el.getBoundingClientRect();
                return {
                    tagName: el.tagName.toLowerCase(),
                    id: el.id || null,
                    testId: el.getAttribute('data-testid') || null,
                    className: el.className || null,
                    ariaLabel: el.getAttribute('aria-label') || null,
                    ariaRole: el.getAttribute('role') || null,
                    name: el.getAttribute('name') || null,
                    placeholder: el.getAttribute('placeholder') || null,
                    textContent: (el.textContent || '').trim().substring(0, 100) || null,
                    href: el.href || null,
                    type: el.type || null,
                    boundingBox: { x: rect.x, y: rect.y, width: rect.width, height: rect.height },
                    parentTag: el.parentElement ? el.parentElement.tagName.toLowerCase() : null,
                    siblingIndex: el.parentElement ? Array.from(el.parentElement.children).indexOf(el) : -1,
                    childCount: el.children.length
                };
            """, element) or {}
        except Exception:
            return {}
`;

    // ── healing_webdriver.py ──────────────────────────────────────────────
    files['tests/healing/healing_webdriver.py'] = `"""Self-healing WebDriver proxy. Auto-generated by qabot.

Intercepts find_element() calls. On failure: requests healed selector
from qabot API. On success: stores element fingerprint as baseline.

Usage:
    from selenium import webdriver
    from healing import HealingWebDriver

    raw_driver = webdriver.Chrome()
    driver = HealingWebDriver(raw_driver)
    driver.find_element(By.CSS_SELECTOR, "#submit")  # auto-heals on failure
"""
from typing import List
from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from .healing_client import HealingClient
from .element_fingerprinter import ElementFingerprinter
from .healing_config import HealingConfig


class HealingWebDriver:
    """Self-healing WebDriver proxy."""

    def __init__(self, delegate: WebDriver):
        self._delegate = delegate
        self._client = HealingClient()

    def find_element(self, by: str = By.ID, value: str = "") -> WebElement:
        if not HealingConfig.ENABLED:
            return self._delegate.find_element(by, value)

        try:
            element = self._delegate.find_element(by, value)
            # Success — store fingerprint as baseline
            self._store_baseline(by, value, element)
            return element
        except NoSuchElementException as e:
            return self._try_heal(by, value, e)

    def find_elements(self, by: str = By.ID, value: str = "") -> List[WebElement]:
        return self._delegate.find_elements(by, value)

    def _try_heal(self, by: str, value: str, original_error: NoSuchElementException) -> WebElement:
        import time
        selector = self._extract_selector(by, value)
        selector_key = f"css:{selector}"
        page_url = self._delegate.current_url
        start = time.time()
        err_msg = str(original_error)

        # Phase 1: Deterministic candidates (fingerprint, similarSelector, textMatch, ancestorSearch)
        result = self._client.resolve(selector, page_url, error_message=err_msg)
        if result and result.selector and result.selector != selector:
            candidates = [{"selector": result.selector, "strategy": result.strategy or "fingerprint"}]
            for c in (result.candidates or []):
                if c.get("selector") and c["selector"] != selector and c["selector"] != result.selector:
                    candidates.append(c)

            for i, candidate in enumerate(candidates):
                label = "Trying" if i == 0 else "Fallback"
                print(f'[qabot-heal] {label}: "{selector}" -> "{candidate["selector"]}" '
                      f'(strategy: {candidate["strategy"]}'
                      f'{f", attempt {i+1}/{len(candidates)}" if i > 0 else ""})')
                try:
                    healed = self._delegate.find_element(By.CSS_SELECTOR, candidate["selector"])
                    duration = int((time.time() - start) * 1000)
                    self._client.report(selector_key, page_url, True,
                                        candidate["selector"], result.confidence, candidate["strategy"])
                    self._store_baseline(By.CSS_SELECTOR, candidate["selector"], healed)
                    return healed
                except NoSuchElementException:
                    pass  # try next candidate

        # Phase 2: AI text-based healing (LLM fallback)
        try:
            ai_result = self._client.resolve_ai(selector, page_url, err_msg)
            if ai_result and ai_result.selector and ai_result.selector != selector:
                print(f'[qabot-heal] AI: "{selector}" -> "{ai_result.selector}" '
                      f'(confidence: {ai_result.confidence}, strategy: aiHealing)')
                try:
                    healed = self._delegate.find_element(By.CSS_SELECTOR, ai_result.selector)
                    duration = int((time.time() - start) * 1000)
                    self._client.report(selector_key, page_url, True,
                                        ai_result.selector, ai_result.confidence, "aiHealing")
                    self._store_baseline(By.CSS_SELECTOR, ai_result.selector, healed)
                    return healed
                except NoSuchElementException:
                    pass  # AI suggestion didn't work
        except Exception:
            pass  # AI healing unavailable

        # Phase 3: Vision healing (screenshot + multimodal LLM)
        try:
            b64 = self._delegate.get_screenshot_as_base64()
            vision_result = self._client.resolve_vision(selector, page_url, b64)
            if vision_result and vision_result.selector and vision_result.selector != selector:
                print(f'[qabot-heal] Vision: "{selector}" -> "{vision_result.selector}" '
                      f'(confidence: {vision_result.confidence}, strategy: visionHealing)')
                try:
                    healed = self._delegate.find_element(By.CSS_SELECTOR, vision_result.selector)
                    duration = int((time.time() - start) * 1000)
                    self._client.report(selector_key, page_url, True,
                                        vision_result.selector, vision_result.confidence, "visionHealing")
                    self._store_baseline(By.CSS_SELECTOR, vision_result.selector, healed)
                    return healed
                except NoSuchElementException:
                    pass  # Vision suggestion didn't work
        except Exception:
            pass  # Screenshot or vision healing unavailable

        # All strategies exhausted
        duration = int((time.time() - start) * 1000)
        self._client.report(selector_key, page_url, False)
        raise original_error

    def _store_baseline(self, by: str, value: str, element: WebElement) -> None:
        try:
            selector = self._extract_selector(by, value)
            selector_key = f"css:{selector}"
            fp = ElementFingerprinter.capture(self._delegate, element)
            if fp:
                self._client.store_fingerprint(selector_key, self._delegate.current_url, fp)
        except Exception:
            pass

    @staticmethod
    def _extract_selector(by: str, value: str) -> str:
        if by == By.CSS_SELECTOR:
            return value
        if by == By.ID:
            return f"#{value}"
        if by == By.NAME:
            return f'[name="{value}"]'
        if by == By.CLASS_NAME:
            return f".{value}"
        if by == By.TAG_NAME:
            return value
        return value

    # ── Delegate all other WebDriver methods ────────────────────────────

    def get(self, url: str) -> None:
        self._delegate.get(url)

    @property
    def current_url(self) -> str:
        return self._delegate.current_url

    @property
    def title(self) -> str:
        return self._delegate.title

    @property
    def page_source(self) -> str:
        return self._delegate.page_source

    def close(self) -> None:
        self._delegate.close()

    def quit(self) -> None:
        self._delegate.quit()

    @property
    def window_handles(self):
        return self._delegate.window_handles

    @property
    def current_window_handle(self):
        return self._delegate.current_window_handle

    def switch_to(self):
        return self._delegate.switch_to

    def back(self) -> None:
        self._delegate.back()

    def forward(self) -> None:
        self._delegate.forward()

    def refresh(self) -> None:
        self._delegate.refresh()

    def execute_script(self, script, *args):
        return self._delegate.execute_script(script, *args)

    def execute_async_script(self, script, *args):
        return self._delegate.execute_async_script(script, *args)

    def save_screenshot(self, filename: str) -> bool:
        return self._delegate.save_screenshot(filename)

    def set_window_size(self, width: int, height: int, windowHandle: str = "current") -> None:
        self._delegate.set_window_size(width, height, windowHandle)

    def maximize_window(self) -> None:
        self._delegate.maximize_window()

    def implicitly_wait(self, time_to_wait: float) -> None:
        self._delegate.implicitly_wait(time_to_wait)

    def __getattr__(self, name):
        """Fallback: delegate any unhandled attributes to the wrapped driver."""
        return getattr(self._delegate, name)
`;

    // ── conftest_healing.py ───────────────────────────────────────────────
    files['tests/healing/conftest_healing.py'] = `"""pytest fixture for self-healing WebDriver. Auto-generated by qabot.

Usage — add to your conftest.py:

    from healing.conftest_healing import healing_driver

Or copy the fixture into your existing conftest.py.

Example test:

    def test_login(healing_driver):
        healing_driver.get("https://example.com")
        healing_driver.find_element(By.CSS_SELECTOR, "#username").send_keys("admin")
"""
import pytest
from selenium import webdriver
from .healing_webdriver import HealingWebDriver
from .healing_config import HealingConfig


@pytest.fixture
def healing_driver():
    """Create a self-healing Chrome WebDriver."""
    options = webdriver.ChromeOptions()
    raw_driver = webdriver.Chrome(options=options)
    driver = HealingWebDriver(raw_driver)
    yield driver
    driver.quit()


@pytest.fixture(autouse=True)
def _healing_log(request):
    """Log healing status for each test."""
    if HealingConfig.ENABLED:
        print(f"[qabot-heal] Self-healing enabled for: {request.node.name}")
    yield
    if hasattr(request.node, "rep_call") and request.node.rep_call.failed:
        print(f"[qabot-heal] Test failed: {request.node.name}"
              f" — check healing dashboard at {HealingConfig.HEALING_SERVER_URL}/healing")
`;

    return files;
  },

  getIntegrationInstructions(config: HealingAdapterConfig): string {
    return `
## Selenium Python Self-Healing Integration

### Generated Files:
- tests/healing/__init__.py — Package init
- tests/healing/healing_config.py — Configuration
- tests/healing/healing_client.py — HTTP client for qabot API
- tests/healing/element_fingerprinter.py — Element attribute capture
- tests/healing/healing_webdriver.py — Self-healing WebDriver proxy
- tests/healing/conftest_healing.py — pytest fixture

### Usage:
1. Start qabot UI server: \`qabot /buildUI\` or \`qabot\` then \`/ui\`
2. Wrap your WebDriver with HealingWebDriver:

   \`\`\`python
   # Before:
   driver = webdriver.Chrome()

   # After:
   from healing import HealingWebDriver
   driver = HealingWebDriver(webdriver.Chrome())
   \`\`\`

   Or use the pytest fixture:
   \`\`\`python
   # In conftest.py:
   from healing.conftest_healing import healing_driver

   def test_login(healing_driver):
       healing_driver.get("https://example.com")
       healing_driver.find_element(By.CSS_SELECTOR, "#submit")  # auto-heals
   \`\`\`

3. All find_element() calls will now auto-heal on failure
4. View healing stats at ${config.healingServerUrl}/healing

### How It Works:
- On find_element() success: captures element fingerprint → stores via qabot API
- On NoSuchElementException: requests healed selector from qabot → retries
- Logs: [qabot-heal] Healed: "#old" → "[data-testid=\\"new\\"]"
`.trim();
  },
};
