import type { HealingAdapter, HealingAdapterConfig } from './base.js';

/**
 * WebdriverIO TypeScript healing adapter.
 *
 * Generates:
 * 1. test/helpers/healing-config.ts — Configuration
 * 2. test/helpers/healing-client.ts — HTTP client
 * 3. test/helpers/healing-service.ts — WDIO Service plugin
 */
export const webdriverioTsAdapter: HealingAdapter = {
  framework: 'webdriverio',
  language: 'typescript',
  displayName: 'WebdriverIO (TypeScript)',

  generate(config: HealingAdapterConfig): Record<string, string> {
    const files: Record<string, string> = {};

    // ── healing-config.ts ─────────────────────────────────────────────
    files['test/helpers/healing-config.ts'] = `// qabot Self-Healing Configuration. Auto-generated by qabot.
export const HealingConfig = {
  HEALING_SERVER_URL: '${config.healingServerUrl}',
  CONFIDENCE_THRESHOLD: ${config.confidenceThreshold},
  AI_ENABLED: ${config.enableAIFallback},
  ENABLED: true,
  FRAMEWORK: 'webdriverio',
  LANGUAGE: 'typescript',
} as const;
`;

    // ── healing-client.ts ─────────────────────────────────────────────
    files['test/helpers/healing-client.ts'] = `// qabot Healing HTTP Client. Auto-generated by qabot.
import { HealingConfig } from './healing-config';

interface HealCandidate {
  selector: string;
  strategy: string;
}

interface HealResult {
  healed: boolean;
  selector?: string;
  selectorStrategy?: string;
  confidence?: number;
  strategy?: string;
  durationMs?: number;
  candidates?: HealCandidate[];
}

export class HealingClient {
  private serverUrl: string;

  constructor(serverUrl?: string) {
    this.serverUrl = serverUrl || HealingConfig.HEALING_SERVER_URL;
  }

  async resolve(selector: string, pageUrl: string, errorMessage?: string): Promise<HealResult | null> {
    try {
      const res = await fetch(\`\${this.serverUrl}/api/heal/resolve\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          selector,
          selectorStrategy: 'css',
          pageUrl,
          framework: HealingConfig.FRAMEWORK,
          language: HealingConfig.LANGUAGE,
          errorMessage,
        }),
        signal: AbortSignal.timeout(5000),
      });
      if (res.ok) return await res.json() as HealResult;
    } catch { /* server not running */ }
    return null;
  }

  async storeFingerprint(selectorKey: string, url: string, fingerprint: Record<string, unknown>): Promise<void> {
    try {
      await fetch(\`\${this.serverUrl}/api/heal/fingerprint\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ selectorKey, url, fingerprint, framework: HealingConfig.FRAMEWORK }),
        signal: AbortSignal.timeout(5000),
      });
    } catch { /* ignore */ }
  }

  async resolveAI(selector: string, pageUrl: string, errorMessage?: string, testContext?: { testName?: string; stepName?: string; scenarioName?: string; actionType?: string }): Promise<HealResult | null> {
    try {
      const res = await fetch(\`\${this.serverUrl}/api/heal/resolve\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          selector,
          selectorStrategy: 'css',
          pageUrl,
          framework: HealingConfig.FRAMEWORK,
          language: HealingConfig.LANGUAGE,
          errorMessage,
          requestAI: true,
          testContext,
        }),
        signal: AbortSignal.timeout(10000),
      });
      if (res.ok) {
        const data = await res.json() as HealResult;
        return data.healed ? data : null;
      }
    } catch { /* AI unavailable */ }
    return null;
  }

  async resolveVision(selector: string, pageUrl: string, screenshotBase64: string, testContext?: { testName?: string; stepName?: string; scenarioName?: string; actionType?: string; errorMessage?: string }): Promise<HealResult | null> {
    try {
      const res = await fetch(\`\${this.serverUrl}/api/heal/vision\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          selector,
          pageUrl,
          screenshotBase64,
          framework: HealingConfig.FRAMEWORK,
          language: HealingConfig.LANGUAGE,
          errorMessage: testContext?.errorMessage,
          testContext,
        }),
        signal: AbortSignal.timeout(15000),
      });
      if (res.ok) {
        const data = await res.json() as HealResult;
        return data.healed ? data : null;
      }
    } catch { /* Vision unavailable */ }
    return null;
  }

  async report(selectorKey: string, url: string, healed: boolean,
    healedSelector?: string, confidence?: number, strategy?: string): Promise<void> {
    try {
      await fetch(\`\${this.serverUrl}/api/heal/report\`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          selectorKey, url, healed, healedSelector, confidence, strategy,
          framework: HealingConfig.FRAMEWORK, language: HealingConfig.LANGUAGE,
          originalSelector: selectorKey,
        }),
        signal: AbortSignal.timeout(5000),
      });
    } catch { /* ignore */ }
  }
}
`;

    // ── healing-service.ts ────────────────────────────────────────────
    files['test/helpers/healing-service.ts'] = `// qabot Self-Healing WDIO Service. Auto-generated by qabot.
//
// Add to wdio.conf.ts:
//   import { HealingService } from './test/helpers/healing-service';
//   services: [[HealingService, {}]],
//
import type { Services, Frameworks } from '@wdio/types';
import { HealingClient } from './healing-client';
import { HealingConfig } from './healing-config';

export class HealingService implements Services.ServiceInstance {
  private client = new HealingClient();
  private lastSelector = '';
  private lastPageUrl = '';
  private lastCommand = '';

  /**
   * Before each WebdriverIO command, capture the selector being used.
   */
  async beforeCommand(commandName: string, args: unknown[]) {
    if (!HealingConfig.ENABLED) return;

    this.lastCommand = commandName;

    // Track $() and $$() calls
    if ((commandName === '$' || commandName === '$$') && typeof args[0] === 'string') {
      this.lastSelector = args[0] as string;
      this.lastPageUrl = await browser.getUrl();
    }
  }

  /**
   * After a successful element find, store the fingerprint.
   */
  async afterCommand(commandName: string, args: unknown[], result: unknown) {
    if (!HealingConfig.ENABLED) return;

    if ((commandName === '$' || commandName === '$$') && typeof args[0] === 'string' && result) {
      try {
        const selector = args[0] as string;
        const selectorKey = \`css:\${selector}\`;
        const url = await browser.getUrl();

        // Capture fingerprint via browser.execute (string-based to avoid TS2584 DOM type errors)
        const fp = await browser.execute(\`(() => {
          const el = document.querySelector('\${selector.replace(/\\\\/g, '\\\\\\\\').replace(/'/g, "\\\\'")}');
          if (!el) return null;
          const rect = el.getBoundingClientRect();
          return {
            tagName: el.tagName.toLowerCase(),
            id: el.id || null,
            testId: el.getAttribute('data-testid') || null,
            className: el.className || null,
            ariaLabel: el.getAttribute('aria-label') || null,
            ariaRole: el.getAttribute('role') || null,
            name: el.getAttribute('name') || null,
            placeholder: el.getAttribute('placeholder') || null,
            textContent: (el.textContent || '').trim().substring(0, 100) || null,
            type: el.type || null,
            boundingBox: { x: rect.x, y: rect.y, width: rect.width, height: rect.height },
            parentTag: el.parentElement ? el.parentElement.tagName.toLowerCase() : null,
            siblingIndex: el.parentElement ? Array.from(el.parentElement.children).indexOf(el) : -1,
            childCount: el.children.length,
          };
        })()\`);

        if (fp) {
          await this.client.storeFingerprint(selectorKey, url, fp);
        }
      } catch { /* fingerprinting failed — continue silently */ }
    }
  }

  /**
   * On element-not-found errors, attempt healing.
   */
  async onError(error: Error, _caps: WebdriverIO.Capabilities) {
    if (!HealingConfig.ENABLED) return;

    // Check if this is an element-not-found error
    const isNotFound = error.name === 'NoSuchElement' ||
      error.message.includes('no such element') ||
      error.message.includes('element could not be located');

    if (!isNotFound || !this.lastSelector) return;

    const errMsg = error instanceof Error ? error.message : '';
    const selectorKey = \`css:\${this.lastSelector}\`;
    const testContext = { actionType: this.lastCommand || undefined };

    // ── Phase 1: Deterministic candidates (fingerprint, similarSelector, textMatch, ancestorSearch) ──
    try {
      const result = await this.client.resolve(this.lastSelector, this.lastPageUrl, errMsg);
      if (result && result.healed && result.selector && result.selector !== this.lastSelector) {
        const candidates: Array<{ selector: string; strategy: string }> = [
          { selector: result.selector, strategy: result.strategy || 'fingerprint' },
        ];
        if (result.candidates) {
          for (const c of result.candidates) {
            if (c.selector !== this.lastSelector && c.selector !== result.selector) candidates.push(c);
          }
        }
        for (let i = 0; i < candidates.length; i++) {
          const cand = candidates[i]!;
          console.log(\`[qabot-heal] \${i === 0 ? 'Trying' : 'Fallback'}: "\${this.lastSelector}" → "\${cand.selector}" (strategy: \${cand.strategy})\`);
        }
        await this.client.report(selectorKey, this.lastPageUrl, true, result.selector, result.confidence, result.strategy);
        // Note: WDIO services can't directly retry commands.
        // Use the heal$() wrapper (see integration instructions) for auto-retry.
        return;
      }
    } catch { /* resolve failed */ }

    // ── Phase 2: AI text-based healing ──
    try {
      const aiResult = await this.client.resolveAI(this.lastSelector, this.lastPageUrl, errMsg, testContext);
      if (aiResult && aiResult.selector && aiResult.selector !== this.lastSelector) {
        console.log(\`[qabot-heal] AI: "\${this.lastSelector}" → "\${aiResult.selector}" (strategy: aiHealing)\`);
        await this.client.report(selectorKey, this.lastPageUrl, true, aiResult.selector, aiResult.confidence, 'aiHealing');
        return;
      }
    } catch { /* AI unavailable */ }

    // ── Phase 3: Vision healing (screenshot + multimodal LLM) ──
    try {
      const screenshotBase64 = await browser.takeScreenshot();
      const visionCtx = { ...testContext, errorMessage: errMsg };
      const visionResult = await this.client.resolveVision(this.lastSelector, this.lastPageUrl, screenshotBase64, visionCtx);
      if (visionResult && visionResult.selector && visionResult.selector !== this.lastSelector) {
        console.log(\`[qabot-heal] Vision: "\${this.lastSelector}" → "\${visionResult.selector}" (strategy: visionHealing)\`);
        await this.client.report(selectorKey, this.lastPageUrl, true, visionResult.selector, visionResult.confidence, 'visionHealing');
        return;
      }
    } catch { /* Vision unavailable */ }

    // All strategies exhausted — report failure
    try {
      await this.client.report(selectorKey, this.lastPageUrl, false);
    } catch { /* ignore */ }
  }
}
`;

    return files;
  },

  getIntegrationInstructions(config: HealingAdapterConfig): string {
    return `
## WebdriverIO Self-Healing Integration

### Generated Files:
- test/helpers/healing-config.ts — Configuration
- test/helpers/healing-client.ts — HTTP client
- test/helpers/healing-service.ts — WDIO Service plugin

### Setup:
1. Start qabot UI server: \`qabot /buildUI\` or \`qabot\` then \`/ui\`

2. Add the service to \`wdio.conf.ts\`:
   \`\`\`typescript
   import { HealingService } from './test/helpers/healing-service';

   export const config: WebdriverIO.Config = {
     services: [[HealingService, {}]],
     // ... rest of config
   };
   \`\`\`

3. The service automatically:
   - Stores element fingerprints on successful \`$()\` calls
   - Attempts healing on element-not-found errors
   - Logs healed selectors to console

4. View healing stats at ${config.healingServerUrl}/healing

### Optional: Custom $ wrapper for auto-retry (3-phase healing)
For automatic retry with healed selectors, add to your test helper:
\`\`\`typescript
import { HealingClient } from './test/helpers/healing-client';

const client = new HealingClient();

export async function heal$(selector: string, testContext?: { testName?: string; stepName?: string; scenarioName?: string; actionType?: string }) {
  try {
    return await $(selector);
  } catch (error) {
    const url = await browser.getUrl();
    const selectorKey = \\\`css:\\\${selector}\\\`;
    const errMsg = error instanceof Error ? error.message : '';

    // Phase 1: Deterministic candidates
    const result = await client.resolve(selector, url, errMsg);
    if (result?.healed && result.selector && result.selector !== selector) {
      const candidates = [
        { selector: result.selector, strategy: result.strategy || 'fingerprint' },
        ...(result.candidates || []).filter(c => c.selector !== selector && c.selector !== result.selector),
      ];
      for (const cand of candidates) {
        try {
          const el = await $(cand.selector);
          await client.report(selectorKey, url, true, cand.selector, result.confidence, cand.strategy);
          return el;
        } catch { /* try next */ }
      }
    }

    // Phase 2: AI text-based healing
    try {
      const aiResult = await client.resolveAI(selector, url, errMsg, testContext);
      if (aiResult?.selector && aiResult.selector !== selector) {
        try {
          const el = await $(aiResult.selector);
          await client.report(selectorKey, url, true, aiResult.selector, aiResult.confidence, 'aiHealing');
          return el;
        } catch { /* try vision */ }
      }
    } catch { /* AI unavailable */ }

    // Phase 3: Vision healing
    try {
      const screenshotBase64 = await browser.takeScreenshot();
      const visionCtx = { ...testContext, errorMessage: errMsg };
      const visionResult = await client.resolveVision(selector, url, screenshotBase64, visionCtx);
      if (visionResult?.selector && visionResult.selector !== selector) {
        try {
          const el = await $(visionResult.selector);
          await client.report(selectorKey, url, true, visionResult.selector, visionResult.confidence, 'visionHealing');
          return el;
        } catch { /* vision failed too */ }
      }
    } catch { /* Vision unavailable */ }

    await client.report(selectorKey, url, false);
    throw error;
  }
}
\`\`\`
`.trim();
  },
};
